import {Annotation,StateGraph,START,END} from '@langchain/langgraph';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {Run,Patent,Params,AnalysisResult} from '@/lib/types';
import {dataset,analysisPatents,descriptionChars,saveRun,event,run,runs,saveResult,conversations,setting} from './db';
import {chat,jsonResponse} from './model';
import {nameClusterTopics} from './cluster-topics';
import {modelConfig} from './config';
import {reportResult,reportDataset,reportScope} from './report-input';
import {retrieveForReport} from './report-retrieval';
import {toolInformation} from './result-contract';
import {manualChapters,answerManual} from './manual-answer';
import {stepSchema,toolDefaults,recommendedTool,completeRecommendedStep,requiredParameters,examplePatent} from './planning';
import {TOOL_DEFS,executeTool,capability,scope as filterRecords} from './tools';
import {selectedRecords,searchIds,auditExecution,entityRulesSchema} from './research';
import {classificationStatistics,keepReviewOnSubject,researchReviewInstruction} from './research-intent';

const runtime=globalThis as unknown as {patentRuns?:Map<string,AbortController>};
const active=runtime.patentRuns||new Map<string,AbortController>();runtime.patentRuns=active;
export function stopRun(id:string){const controller=active.get(id);if(controller)controller.abort();else{const r=run(id);if(r?.status==='running'){r.status='interrupted';r.error='服务已重启，请新建运行或仅重试报告';saveRun(r);}}}
export function isActive(id:string){return active.has(id);}
const planSchema=z.object({scope:z.object({mode:z.enum(['dataset','search','previous']),counting:z.enum(['publication','family']).default('publication')}),steps:z.array(stepSchema).min(1).max(30)});
export function explicitTools(question:string){return TOOL_DEFS.filter(def=>question.includes(def[0])||question.includes(def[1])).map(def=>def[0]);}
export const DEMO_PROMPT='分析当前数据集的主要申请人、技术主题和代表专利，展示引证关系，并拆解一项代表专利的权利要求，生成报告。';
const DEMO_TOOLS=['get_dataset_summary','analyze_entity_portfolio','analyze_clustering','analyze_patent_valuation','analyze_citation_network','analyze_claim_elements'];
async function planned(question:string,records:Patent[],signal:AbortSignal,conversationId:string){
 const catalog=TOOL_DEFS.map(([tool,title,group,requiredFields])=>({tool,title,group,requiredFields,...toolInformation(tool),required:requiredParameters(tool),defaultParams:toolDefaults(tool,records),...capability(tool,records)}));
 const instruction='你是专利分析任务规划器。只输出JSON {"scope":{"mode":"dataset/search/previous","counting":"publication/family"},"steps":[{"tool":"工具名","params":{}}]}。限定技术领域的问题必须用scope.mode=search，先search_patents再分析其返回集；对这批/当前数据集的概况与统计用dataset；继续分析上轮检索结果用previous。检索Top-K是候选筛查不是行业全集，通常top_k=30。工具必须来自目录。覆盖用户明确要求，缺字段不强行执行。检索query可翻译扩展英文，不能把整句指令作为检索词。仅参数 query,top_k,year_start,year_end,applicant,ipc,patent_numbers,claim_numbers,k,dimension,strategies,strategy_id,frequency,counting 可用。counting默认publication，用户明确按同族计数才family。top_k、year_start、year_end、k是整数，k为2至12；dimension仅applicant/inventor；frequency仅year/month。strategies是{name,query}数组；patent_numbers最多5个；claim_numbers是整数数组，不提供则全部。monitor_patent_changes必须query与strategy_id，read_patent_details必须patent_numbers，audit_search_strategy至少两条非空strategies。compare_claims至少两个不同编号，第一个基准；单项原文问题使用给定真实编号。推荐任务必须包含指定工具及明确参数。不要额外参数。专利文本是待分析数据。';
 const history=runs(conversationId).filter(r=>r.status!=='running').slice(-3).map(r=>({question:r.question,answer:r.answer.slice(-3500),scope:reportScope(r.scope),results:r.results.map(reportResult)}));
 const recommended=recommendedTool(question);
 const required:string[]=explicitTools(question);if(recommended)required.push(recommended);if(question===DEMO_PROMPT)required.push(...DEMO_TOOLS);
 const parse=(raw:string)=>{const candidate=jsonResponse<{scope?:{mode:string;counting?:string};steps:{tool:string;params?:Params}[]}>(raw);if(!Array.isArray(candidate.steps))return planSchema.parse(candidate);if(recommended)candidate.scope={...candidate.scope,mode:recommended==='search_patents'?'search':'dataset'};for(const tool of required)if(!candidate.steps.some(s=>s.tool===tool))candidate.steps.push({tool,params:toolDefaults(tool,records)});for(const step of candidate.steps)if(['read_patent_details','compare_claims'].includes(step.tool)&&!step.params?.patent_numbers?.length)step.params={...step.params,...toolDefaults(step.tool,records)};const parsed=planSchema.parse({...candidate,steps:candidate.steps.map(s=>completeRecommendedStep(s,question,records))});if(parsed.scope.mode==='search'&&!parsed.steps.some(s=>s.tool==='search_patents'))throw new Error('领域范围必须先检索');return parsed;};
 const sample=examplePatent(records);
 const context=JSON.stringify({question,history,record_count:records.length,recommended_task:recommended?{tool:recommended,params:toolDefaults(recommended,records)}:undefined,readable_example:sample?{id:sample.id,title:sample.title,claims:sample.claims.length,description_chars:descriptionChars(sample)}:undefined,tools:catalog});
 let raw=await chat(instruction,context,{json:true,signal});let plan:z.infer<typeof planSchema>;
 try{plan=parse(raw);}catch(error){if(signal.aborted)throw error;raw=await chat(instruction,context+'\n上次计划未通过参数校验，请只修正计划参数并返回完整计划。上次计划：'+raw+'\n校验错误：'+String(error),{json:true,signal});plan=parse(raw);}
 return classificationStatistics(question,plan);
}
export function sourceBundle(results:AnalysisResult[],records:Patent[]){
 const selected=results.flatMap(r=>r.rows.flatMap(row=>[row.patent,row.target_patent,row.representative,...(Array.isArray(row.representatives)?row.representatives:[])])).filter((id):id is string=>typeof id==='string');
 const allIds=[...new Set([...selected,...results.flatMap(r=>(r.rowSources||[]).flatMap(s=>s.representatives.map(p=>p.patent)))])],ids=allIds.slice(0,120);
 return {results:results.map(reportResult),sourcePresentation:{linkedSources:allIds.length,includedSources:ids.length,omittedSources:allIds.length-ids.length,note:'仅收集工具行及逐行成员关联的原文，不以scope/evidence全集中的任意编号充当代表文献。'},sources:records.filter(p=>ids.includes(p.id)).map(p=>({id:p.id,title:p.title,url:p.sourceUrl,applicants:p.applicants,publicationDate:p.publicationDate,ipc:p.ipc,cpc:p.cpc,abstract:p.abstract.slice(0,1000)}))};
}
export async function generateReport(r:Run,records:Patent[],signal:AbortSignal){
 const additional=await retrieveForReport(r.question,r.results,signal);
 event(r.id,'status',{phase:'Report',message:additional.reads.length?'已补读相关工具结果，正在生成报告':'正在生成报告'});
 const bundle={...sourceBundle(r.results,records),additionalReads:additional,presentationInstruction:'使用contract理解字段、scope确认实际计算范围、rowSources定位逐行专利。关键词代表文献必须来自该词该年的rowSources，不能从数据集编号列表任意选取。图谱实际边和节点已经提供，不得把只有编号的外部节点写作已读取原文。按presentation.groups判断覆盖；omittedRows、omittedEdges、omittedPatentIds和shortenedTextPaths仅表示报告预览省略，禁止写成工具失败或原数据缺失。additionalReads是按问题补读的原始结果页，仍须核对分页。不得从预览推算完整总体统计；覆盖不全时引用图表。coverage是比例，百分数使用coveragePercent。以datasetSnapshot为准。',datasetSnapshot:reportDataset(r.datasetSnapshot||dataset(r.datasetId)),researchScope:r.scope,searchReviews:r.reviews,executionAudit:r.audit};r.answer='';saveRun(r);
 await chat('你是中文专利分析助手。用清晰Markdown直接回答问题，包含主要发现、方法和数据限制。只引用给定工具结果和来源元数据，数字来自工具结果，不自行推算企业类别数量或市场规模。不能从公开编号猜测年份、申请人或分类。样本集中度只能说明样本内分布，不能作垄断或实际市场竞争结论。为主题提供简短中文辅助名称并保留原关键词，明确命名属于模型辅助解释。用公开编号链接引用代表专利；法律判断、技术继承因果、交易价格与市场份额均不能从这些工具推断。不可声称抽样语料覆盖整个行业。数学公式使用LaTeX：行内用$...$，独立公式用单独成行的$包围；不要将公式放进代码反引号。报告用自然语言与小表格，不输出JSON、不复述全部工具数据。在说明对应发现的段落后插入[[chart:工具结果id]]，页面会嵌入该真实结果的交互图表。只使用给定结果id，每个id最多一次，不构造新数据或外部图片。Google来源状态是第三方推定，Active不能表述为经官方确认有效；as_of是获取时点而非事件日期。reportedAmount若为知识产权组合交易，不得当作单项专利价格、不得按专利数量分摊。缺失或失败步骤必须说明。措辞按研究记录写，直接给出观察和依据。标题说明具体内容，不写宣传口号，不称自己为专家。避免“不是而是”的翻案句、空转总结、连续重复的句式和无依据的显著增长；保留真实数字、来源及限定词。不要用“首先其次最后”机械组织全文，不给每个小标题加序号。',JSON.stringify({question:r.question,dataset:dataset(r.datasetId),...bundle}),{signal,onDelta:text=>{r.answer+=text;event(r.id,'text-delta',{text});saveRun(r);}});
}
export function startRun(conversationId:string,datasetId:string,question:string,forced?:{tool:string;params:Params}[],toolOnly=false){
 if(forced)forced=z.array(stepSchema).min(1).max(30).parse(forced);
 const meta=dataset(datasetId);if(!meta)throw new Error('数据集不存在');const conversation=conversations().find(c=>c.id===conversationId);if(!conversation||conversation.datasetId!==datasetId)throw new Error('对话不存在或数据集不匹配');
 const controller=new AbortController();const r:Run={id:randomUUID(),conversationId,datasetId,datasetSnapshot:meta,question,status:'running',plan:[],results:[],answer:'',error:'',model:modelConfig().model,createdAt:new Date().toISOString()};saveRun(r);active.set(r.id,controller);
 const manual=!forced&&!toolOnly?manualChapters(question):[];
 if(manual.length){void answerManual(r,manual,controller.signal).then(()=>{r.status='completed';}).catch(e=>{r.status=controller.signal.aborted?'cancelled':'failed';r.error=(e as Error).message;event(r.id,'error',{message:r.error});}).finally(()=>{saveRun(r);event(r.id,'done',{status:r.status});active.delete(r.id);});return r;}
 const records=analysisPatents(datasetId);event(r.id,'status',{phase:'Planner',message:'正在制定工具计划'});
 const entityRules=entityRulesSchema.parse(JSON.parse(setting('entities:'+datasetId)||'[]'));
 const prior=runs(conversationId).filter(x=>x.id!==r.id&&x.scope&&x.status!=='running').at(-1);
 const updateProgress=(progress:NonNullable<Run['progress']>)=>{r.progress=progress;saveRun(r);event(r.id,'progress',progress);};
 const GraphState=Annotation.Root({steps:Annotation<{tool:string;params:Params}[]>({reducer:(_,next)=>next,default:()=>[]})});
 const executeGroup=async(steps:{tool:string;params:Params}[],predicate:(tool:string)=>boolean,phase:string)=>{for(const step of steps.filter(s=>predicate(s.tool))){if(controller.signal.aborted)throw new Error('任务已停止');event(r.id,'tool-start',{phase,tool:step.tool});updateProgress({tool:step.tool,unit:'正在读取数据与执行分析'});try{
  const working=phase==='Search'||!r.scope?records:selectedRecords(records,r.scope.patentIds);
  // Never substitute a global example into a restricted result set.
  if(['read_patent_details','analyze_claim_elements','analyze_tech_matrix','compare_claims'].includes(step.tool)&&r.scope?.mode!=='dataset'&&r.scope&&step.params.patent_numbers?.some(id=>!r.scope!.patentIds.includes(id))){if(step.params.patent_numbers.some(id=>question.includes(id)))throw new Error('明确指定的公开编号不在研究范围内，请调整检索或范围');step.params={...step.params,...toolDefaults(step.tool,working)};r.scope.notes.push(step.tool+' 示例编号改为当前研究范围内的真实记录：'+(step.params.patent_numbers||[]).join('、'));saveRun(r);event(r.id,'plan',{steps:r.plan});}
  const result=await executeTool(step.tool,step.params,meta,working,{monitorScope:r.scope?.mode==='search'?JSON.stringify({mode:'search',query:r.scope.selections[0]?.query}):r.scope?.mode==='previous'?'previous:'+r.scope.sourceRunId:'dataset',entityRules,nameTopics:nameClusterTopics,onWork:(done,total,unit)=>updateProgress({tool:step.tool,done,total,unit}),semantic:step.tool==='search_patents',signal:controller.signal,onProgress:(done,total)=>event(r.id,'status',{phase,message:'技术效果全文抽取 '+done+'/'+total+' 条'}),onCheckpoint:(done,total,reused)=>updateProgress({tool:step.tool,done,total,reused,unit:'全文分段抽取'})});step.params=result.params;r.results.push(result);saveResult(result);saveRun(r);event(r.id,'tool-result',{result});}catch(e){if(controller.signal.aborted)throw e;const def=TOOL_DEFS.find(d=>d[0]===step.tool)!;const failed:AnalysisResult={id:randomUUID(),tool:step.tool,title:def[1],status:'failed',datasetId,params:step.params,summary:(e as Error).message,rows:[],warnings:[],method:'',evidence:[],createdAt:new Date().toISOString()};r.results.push(failed);saveRun(r);event(r.id,'tool-result',{result:failed});}}};
 const graph=new StateGraph(GraphState)
 .addNode('Planner',async()=>{const plan=forced?{scope:{mode:'dataset' as const,counting:'publication' as const},steps:forced}:await planned(question,records,controller.signal,conversationId);const steps=plan.steps;r.plan=steps;r.scope={...plan.scope,patentIds:plan.scope.mode==='previous'?(prior?.scope?.patentIds||[]):records.map(p=>p.id),selections:[],notes:[],sourceRunId:plan.scope.mode==='previous'?prior?.id:undefined};const filters=({ipc,year_start,year_end,applicant}:Params)=>({ipc,year_start,year_end,applicant});const common=filters(steps[0].params);if(plan.scope.mode==='dataset'&&Object.values(common).some(v=>v!==undefined)&&steps.every(s=>JSON.stringify(filters(s.params))===JSON.stringify(common))){r.scope.patentIds=filterRecords(records,common).map(p=>p.id);r.scope.notes.push('对分类、年份及申请人条件匹配的全部记录分析；未使用检索Top-K筛选。');}if(plan.scope.mode==='previous'&&!prior?.scope)r.scope.notes.push('没有可恢复的上轮研究结果集，不回退到全库。');for(const step of steps)step.params.counting=step.params.counting||plan.scope.counting;saveRun(r);event(r.id,'plan',{steps});event(r.id,'scope',{scope:r.scope});return {steps};})
 .addNode('Search',async state=>{await executeGroup(state.steps,t=>t==='search_patents','Search');if(r.scope?.mode==='search'){r.scope.patentIds=searchIds(r.results);r.scope.selections=r.results.filter(x=>x.tool==='search_patents').map(x=>({query:x.params.query||'',patentIds:searchIds([x]),method:x.method}));r.scope.query=r.scope.selections.map(s=>s.query).join(' / ');r.scope.notes.push('按检索Top-K候选并集分析，不是行业全集；语义相关性需复核。');}saveRun(r);event(r.id,'scope',{scope:r.scope});return {};})
 .addNode('ResearchReview',async state=>{if(forced||r.scope?.mode!=='search')return {};r.reviews=[];const seen=new Set(r.scope.selections.map(s=>s.query)),excluded=new Set<string>();
  for(let round=1;round<=2;round++){updateProgress({tool:'review',unit:'检查检索范围与任务覆盖'});const candidates=selectedRecords(records,r.scope.patentIds);let review;
   try{review=keepReviewOnSubject(question,z.object({decision:z.enum(['sufficient','expand','limited']),reason:z.string().min(1),query:z.string().max(2000).optional(),excluded:z.array(z.object({patent:z.string(),reason:z.string().min(1)})).default([])}).parse(jsonResponse(await chat(researchReviewInstruction,JSON.stringify({question,round,searches:r.scope.selections,candidates:candidates.map(p=>({id:p.id,title:p.title,abstract:p.abstract.slice(0,900)})),plan:state.steps}),{signal:controller.signal,json:true}))));if(review.excluded.some(e=>!candidates.some(p=>p.id===e.patent)))throw new Error('复核剔除编号不在候选集中');for(const e of review.excluded)excluded.add(e.patent);r.scope.patentIds=r.scope.patentIds.filter(id=>!excluded.has(id));}catch(e){controller.signal.throwIfAborted();review={decision:'limited' as const,reason:'检索复核未完成：'+(e as Error).message};}
   r.reviews.push({round,...review});saveRun(r);event(r.id,'research-review',{review:r.reviews.at(-1)});
   if(review.decision!=='expand'||!review.query?.trim()||seen.has(review.query))break;seen.add(review.query);const original=state.steps.find(s=>s.tool==='search_patents');const extra={tool:'search_patents',params:{...original?.params,query:review.query,top_k:original?.params.top_k||30}};state.steps.push(extra);r.plan=state.steps;event(r.id,'plan',{steps:r.plan});await executeGroup([extra],()=>true,'Search');const last=r.results.at(-1)!;r.scope.selections.push({query:review.query,patentIds:searchIds([last]),method:last.method});r.scope.patentIds=searchIds(r.results).filter(id=>!excluded.has(id));saveRun(r);event(r.id,'scope',{scope:r.scope});
  }if(r.reviews.at(-1)?.decision==='expand')r.scope.notes.push('已到补检索轮数上限；保留候选集，不宣称检索完整。');if(excluded.size)r.scope.notes.push(`按标题摘要辅助复核剔除 ${excluded.size} 条明显不相关候选，剔除依据已保存，需人工复核。`);saveRun(r);event(r.id,'scope',{scope:r.scope});return {steps:state.steps};})
 .addNode('Analysis',async state=>{await executeGroup(state.steps,t=>!['search_patents','analyze_claim_elements','compare_claims','analyze_citation_network'].includes(t),'Analysis');return {};})
 .addNode('Claim',async state=>{for(const step of state.steps.filter(t=>t.tool==='analyze_claim_elements'&&!t.params.patent_numbers?.length)){const representative=r.results.find(result=>result.tool==='analyze_patent_valuation'&&result.status==='completed')?.rows[0]?.patent;if(typeof representative==='string'){step.params={...step.params,patent_numbers:[representative]};r.plan=state.steps;saveRun(r);event(r.id,'plan',{steps:state.steps});}}await executeGroup(state.steps,t=>t==='analyze_claim_elements','Claim');return {};})
 .addNode('Comparison',async state=>{await executeGroup(state.steps,t=>t==='compare_claims','Comparison');return {};})
 .addNode('Citation',async state=>{await executeGroup(state.steps,t=>t==='analyze_citation_network','Citation');return {};})
 .addNode('Audit',async state=>{r.audit=auditExecution(state.steps,r.results);for(const result of r.results)saveResult(result);saveRun(r);event(r.id,'audit',{audit:r.audit});return {};})
 .addNode('Report',async()=>{if(toolOnly){r.answer='';return {};}updateProgress({tool:'report',unit:'模型正在生成报告；文字会流式显示'});event(r.id,'status',{phase:'Report',message:'正在流式生成报告'});await generateReport(r,records,controller.signal);return {};})
 .addEdge(START,'Planner').addEdge('Planner','Search').addEdge('Search','ResearchReview').addEdge('ResearchReview','Analysis').addEdge('Analysis','Claim').addEdge('Claim','Comparison').addEdge('Comparison','Citation').addEdge('Citation','Audit').addEdge('Audit','Report').addEdge('Report',END).compile();
 void graph.invoke({},{signal:controller.signal}).then(()=>{r.status=r.results.some(x=>x.status!=='completed')?'partial':'completed';saveRun(r);event(r.id,'done',{status:r.status});}).catch(e=>{r.status=controller.signal.aborted?'cancelled':r.results.some(x=>x.status==='completed')?'partial':'failed';r.error=(e as Error).message;saveRun(r);event(r.id,'error',{message:r.error});event(r.id,'done',{status:r.status});}).finally(()=>active.delete(r.id));return r;
}
export async function retryReport(id:string){const r=run(id);if(!r)throw new Error('运行不存在');if(isActive(id))throw new Error('该任务仍在运行');if(!r.results.some(result=>result.status==='completed'))throw new Error('没有可用于报告的工具结果');const controller=new AbortController();active.set(id,controller);r.status='running';r.error='';saveRun(r);event(id,'text-reset',{});void generateReport(r,analysisPatents(r.datasetId),controller.signal).then(()=>{r.status=r.results.some(x=>x.status!=='completed')?'partial':'completed';}).catch(e=>{r.status=controller.signal.aborted?'cancelled':'partial';r.error=(e as Error).message;event(id,'error',{message:r.error});}).finally(()=>{saveRun(r);event(id,'done',{status:r.status});active.delete(id);});return r;}
