import type {Patent,Graph,Row} from '@/lib/types';
export function count(values:string[]){const counts=new Map<string,number>();for(const value of values)if(value)counts.set(value,(counts.get(value)||0)+1);return [...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));}
const stop=new Set('the a an and or of to in for with by on at from is are be as that this these those it its can may will such said wherein thereof thereof one two first second present invention embodiment embodiments example examples fig figure figures includes including include system systems method methods apparatus device devices configured using based plurality each some also any other more least data comprises comprising processor processing computer patent claim claims'.split(' '));
export function tokens(text:string){return (text.toLowerCase().match(/[a-z][a-z-]{2,}/g)||[]).filter(word=>!stop.has(word));}
export function wordCounts(records:Patent[]){return count(records.flatMap(p=>[...new Set(tokens(p.title+' '+p.abstract))]));}
export function cosine(a:number[],b:number[]){let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i];}return aa&&bb?dot/Math.sqrt(aa*bb):0;}
export function lexical(records:Patent[],query:string){
 const q=[...new Set(tokens(query))];if(!q.length||!records.length)return [];
 const documents=records.map(p=>tokens(p.title+' '+p.abstract)),average=documents.reduce((s,d)=>s+d.length,0)/records.length||1;
 const frequencies=documents.map(d=>new Map(count(d))),idf=new Map(q.map(word=>{const df=frequencies.filter(f=>f.has(word)).length;return [word,Math.log(1+(records.length-df+.5)/(df+.5))];}));
 return records.map((p,i)=>({p,score:q.reduce((sum,word)=>{const tf=frequencies[i].get(word)||0;return sum+idf.get(word)!*tf*2.2/(tf+1.2*(.25+.75*documents[i].length/average));},0)})).filter(r=>r.score>0).sort((a,b)=>b.score-a.score||a.p.id.localeCompare(b.p.id));
}
export function keywordWeights(records:Patent[],reference:Patent[]=records){
 const docs=reference.map(p=>new Set(tokens(p.title+' '+p.abstract))),tf=new Map(count(records.flatMap(p=>tokens(p.title+' '+p.abstract))));
 return wordCounts(records).map(([word,documents])=>({word,documents,tf:tf.get(word)!,tfidf:(1+Math.log(tf.get(word)!))*(1+Math.log((reference.length+1)/(1+docs.filter(d=>d.has(word)).length)))})).sort((a,b)=>b.tfidf-a.tfidf||a.word.localeCompare(b.word));
}
export function kleinbergBursts(records:Patent[],progress?:(done:number,total:number)=>void):Row[]{
 records=records.filter(p=>/^\d{4}/.test(p.publicationDate));if(!records.length)return [];
 const years=[...new Set(records.map(p=>p.publicationDate.slice(0,4)).filter(Boolean))].sort(),batches=years.map(year=>records.filter(p=>p.publicationDate.startsWith(year))),documents=batches.map(batch=>batch.map(p=>new Set(tokens(p.title+' '+p.abstract))));
 const terms=wordCounts(records).filter(([,n])=>n>=2&&n<records.length),rows:Row[]=[];const s=2,gamma=1,penalty=gamma*Math.log(Math.max(2,records.length));
 for(const [index,[word,total]] of terms.entries()){
  const baseline=total/records.length,rates=[baseline];while(rates.at(-1)!*s<1)rates.push(rates.at(-1)!*s);rates.push(1-1e-9);
  const hits=documents.map(batch=>batch.filter(d=>d.has(word)).length),cost=(t:number,state:number)=>-hits[t]*Math.log(rates[state])-(batches[t].length-hits[t])*Math.log(1-rates[state]);
  let previous=rates.map((_,state)=>state*penalty);const parents:number[][]=[];
  for(let t=0;t<years.length;t++){const parent:number[]=[],next=rates.map((_,state)=>{let best=Infinity,from=0;for(let j=0;j<rates.length;j++){const value=previous[j]+Math.max(0,state-j)*penalty;if(value<best){best=value;from=j;}}parent[state]=from;return best+cost(t,state);});parents.push(parent);previous=next;}
  let state=previous.indexOf(Math.min(...previous));const sequence=Array(years.length).fill(0);for(let t=years.length-1;t>=0;t--){sequence[t]=state;state=parents[t][state];}
  for(let level=1;level<rates.length;level++){let start=-1;for(let t=0;t<=years.length;t++){if(t<years.length&&sequence[t]>=level){if(start<0)start=t;}else if(start>=0){const end=t-1,strength=Array.from({length:end-start+1},(_,j)=>cost(start+j,level-1)-cost(start+j,level)).reduce((a,b)=>a+b,0);rows.push({word,start_year:years[start],end_year:years[end],level,burst:strength,documents:hits.slice(start,end+1).reduce((a,b)=>a+b,0),baseline_rate:baseline,burst_rate:rates[level],s,gamma});start=-1;}}}
  progress?.(index+1,terms.length);
 }return rows.sort((a,b)=>Number(b.burst)-Number(a.burst)||String(a.word).localeCompare(String(b.word)));
}
export function lifecycleFit(records:Patent[]){
 const yearly=count(records.map(p=>p.publicationDate.slice(0,4)).filter(year=>/^\d{4}$/.test(year))).sort(([a],[b])=>a.localeCompare(b));let cumulative=0;const points=yearly.map(([year,n])=>({year,count:n,cumulative:cumulative+=n}));if(points.length<6)return {points,fit:null};
 const x=points.map(p=>Number(p.year)-Number(points[0].year)),y=points.map(p=>p.cumulative),max=y.at(-1)!,span=x.at(-1)||1;
 const curve=(p:number[],t:number)=>Math.exp(p[0])/(1+Math.exp(-Math.exp(p[1])*(t-p[2]))),loss=(p:number[])=>y.reduce((sum,value,i)=>sum+(value-curve(p,x[i]))**2,0);
 let best=[Math.log(max*1.5),Math.log(.3),span/2],error=loss(best),steps=[.8,.6,span/3];
 for(let iteration=0;iteration<150;iteration++){let improved=false;for(let d=0;d<3;d++)for(const direction of [-1,1]){const next=best.slice();next[d]+=steps[d]*direction;if(next[0]<Math.log(max)||next[0]>Math.log(max*100)||next[1]<Math.log(.001)||next[1]>Math.log(10)||Math.abs(next[2])>span*20)continue;const candidate=loss(next);if(candidate<error){best=next;error=candidate;improved=true;}}if(!improved)steps=steps.map(step=>step*.85);}
 const mean=y.reduce((a,b)=>a+b,0)/y.length,sst=y.reduce((sum,n)=>sum+(n-mean)**2,0),L=Math.exp(best[0]),k=Math.exp(best[1]);
 return {points:points.map((p,i)=>({...p,fitted_cumulative:curve(best,x[i]),residual:y[i]-curve(best,x[i])})),fit:{asymptote:L,rate:k,inflection_year:Number(points[0].year)+best[2],r_squared:sst?1-error/sst:0,rmse:Math.sqrt(error/y.length),observations:y.length,weakly_identified:L>max*95||best[2]<0||best[2]>span}};
}
export function clusters(records:Patent[],k:number){if(!records.length||records.some(p=>!p.embedding?.length))throw new Error('主题聚类需要完整嵌入索引');k=Math.min(k,records.length);const vectors=records.map(p=>p.embedding!);let seed=42;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};const centroids=[vectors[Math.floor(random()*vectors.length)].slice()];
 while(centroids.length<k){const distances=vectors.map(v=>Math.max(0,1-Math.max(...centroids.map(c=>cosine(v,c))))**2),total=distances.reduce((a,b)=>a+b,0);let n=random()*total,index=0;for(;index<distances.length-1;index++){n-=distances[index];if(n<=0)break;}centroids.push(vectors[index].slice());}
 let labels=Array(records.length).fill(-1) as number[];for(let iteration=0;iteration<30;iteration++){const next=vectors.map(v=>centroids.map(c=>cosine(v,c)).reduce((best,score,i,scores)=>score>scores[best]?i:best,0));if(next.every((label,i)=>label===labels[i]))break;labels=next;centroids.forEach((c,label)=>{const members=vectors.filter((_,i)=>labels[i]===label);if(!members.length)return;c.fill(0);for(const v of members)for(let j=0;j<c.length;j++)c[j]+=v[j]/members.length;});}
 return centroids.map((centroid,label)=>{const members=records.filter((_,i)=>labels[i]===label);return {cluster:label+1,count:members.length,keywords:keywordWeights(members,records).slice(0,6).map(row=>row.word).join(' · '),patents:members.map(p=>p.id),representatives:members.sort((a,b)=>cosine(b.embedding!,centroid)-cosine(a.embedding!,centroid)).slice(0,3).map(p=>p.id)};}).filter(row=>row.count);
}
export function cooperation(records:Patent[],dimension:'applicant'|'inventor'='applicant'):Graph{
 const names=(p:Patent)=>dimension==='inventor'?p.inventors:p.applicants;const edges=new Map<string,number>();for(const p of records){const entities=[...new Set(names(p))].sort();for(let i=0;i<entities.length;i++)for(let j=i+1;j<entities.length;j++){const key=JSON.stringify([entities[i],entities[j]]);edges.set(key,(edges.get(key)||0)+1);}}
 return {nodes:count(records.flatMap(names)).map(([id,value])=>({id,label:id,kind:dimension,value})),edges:[...edges].map(([key,weight])=>{const [source,target]=JSON.parse(key);return {source,target,weight,kind:'cooperation'};})};
}
export const citationKey=(v:string)=>v.toUpperCase().replace(/[^A-Z0-9]/g,'').replace(/[ABCU]\d$/,'');
export function citationGraph(records:Patent[]):Graph{const aliases=new Map(records.map(p=>[citationKey(p.id),p.id]));const nodes=new Map(records.map(p=>[p.id,{id:p.id,label:p.id,kind:'patent',value:1}]));const edges:Graph['edges']=[];for(const p of records)for(const cited of [...new Set(p.citations)]){const target=aliases.get(citationKey(cited))||cited;if(!nodes.has(target))nodes.set(target,{id:target,label:target,kind:'external',value:1});edges.push({source:p.id,target,weight:1,kind:'citation'});nodes.get(target)!.value++;}return {nodes:[...nodes.values()],edges};}
export function coupling(records:Patent[]):Row[]{const rows:Row[]=[];for(let i=0;i<records.length;i++)for(let j=i+1;j<records.length;j++){const a=new Set(records[i].citations.map(citationKey)),shared=[...new Set(records[j].citations.map(citationKey))].filter(id=>a.has(id));if(shared.length)rows.push({source:records[i].id,target:records[j].id,shared:shared.length});}return rows.sort((a,b)=>Number(b.shared)-Number(a.shared)).slice(0,30);}
export function coCitations(records:Patent[]):Row[]{const counts=new Map<string,number>();for(const p of records){const ids=[...new Set(p.citations.map(citationKey))].sort();for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const key=JSON.stringify([ids[i],ids[j]]);counts.set(key,(counts.get(key)||0)+1);}}return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,30).map(([key,value])=>{const [source,target]=JSON.parse(key);return {source,target,count:value};});}
export function pagerank(graph:Graph){const n=graph.nodes.length;if(!n)return new Map<string,number>();let scores=new Map(graph.nodes.map(node=>[node.id,1/n]));const outs=new Map<string,string[]>();for(const e of graph.edges)outs.set(e.source,[...(outs.get(e.source)||[]),e.target]);for(let iteration=0;iteration<40;iteration++){const dangling=[...scores].filter(([id])=>!outs.get(id)?.length).reduce((sum,[,score])=>sum+score,0);const next=new Map(graph.nodes.map(node=>[node.id,(1-0.85)/n+0.85*dangling/n]));for(const [id,targets] of outs)for(const target of targets)next.set(target,next.get(target)!+0.85*scores.get(id)!/targets.length);scores=next;}return scores;}
export function concentration(records:Patent[]){const entities=new Map<string,number>();for(const p of records)for(const name of [...new Set(p.applicants)])entities.set(name,(entities.get(name)||0)+1/p.applicants.length);const total=[...entities.values()].reduce((sum,v)=>sum+v,0);const shares=[...entities.values()].sort((a,b)=>b-a).map(v=>v/(total||1));return {record_count:records.length,entity_count:entities.size,cr3:shares.slice(0,3).reduce((a,b)=>a+b,0),cr5:shares.slice(0,5).reduce((a,b)=>a+b,0),cr10:shares.slice(0,10).reduce((a,b)=>a+b,0),hhi:shares.reduce((sum,v)=>sum+v*v,0),effective_entities:Math.exp(-shares.reduce((sum,v)=>sum+(v?v*Math.log(v):0),0))};}
