import {z} from 'zod';
import {db,dataset,datasets,analysisPatents,patent,updateDataset,setting} from './db';
import {cleanId,normalize,datasetMeta} from './importers';
import {embed} from './model';
const texts=z.array(z.string().trim().min(1));
export const recordSchema=z.object({id:z.string().min(1),title:z.string().trim().min(1),abstract:z.string().default(''),applicants:texts.default([]),assignees:texts.optional(),inventors:texts.optional(),publicationDate:z.string().refine(v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v),'公开日期格式应为 YYYY-MM-DD').default(''),ipc:texts.default([]),cpc:texts.optional(),description:z.string().optional(),claims:z.array(z.object({number:z.number().int().positive(),text:z.string().min(1)})).refine(v=>new Set(v.map(c=>c.number)).size===v.length,'权利要求编号不能重复').optional(),citations:texts.optional(),sourceUrl:z.string().url().optional(),sourceName:z.string().optional()});
export function refreshDataset(id:string){const old=dataset(id);if(!old)throw new Error('数据集不存在');const current=datasetMeta(old.name,analysisPatents(id),old.source,old.sampling);const next={...old,count:current.count,indexed:current.indexed,coverage:current.coverage,years:current.years,warnings:current.warnings};updateDataset(next);return next;}
function clearCheckpoints(id:string,recordId?:string){for(const table of ['claim_checkpoints','effect_checkpoints'])if(db.prepare('SELECT name FROM sqlite_master WHERE name=?').get(table))db.prepare(`DELETE FROM ${table} WHERE dataset_id=?${recordId?' AND patent_id=?':''}`).run(...(recordId?[id,recordId]:[id]));if(db.prepare("SELECT name FROM sqlite_master WHERE name='comparison_checkpoints'").get())db.prepare("DELETE FROM comparison_checkpoints WHERE json_extract(key,'$[1]')=?").run(id);}
export function writeRecord(datasetId:string,input:unknown,existingId?:string){
 if(!dataset(datasetId))throw new Error('数据集不存在');const patch=z.record(z.unknown()).parse(input),previous=existingId?patent(datasetId,existingId):undefined;
 if(existingId&&!previous)throw new Error('记录不存在');const fields=recordSchema.parse({...previous,...patch}),id=cleanId(fields.id);if(!id)throw new Error('公开编号不能为空');if(existingId&&id!==existingId)throw new Error('编辑时不能更改公开编号；请新增记录');if(!existingId&&Boolean(patent(datasetId,id)))throw new Error('公开编号已存在，请使用编辑');
 const next={...previous,...normalize({...previous,...fields},'用户新增'),editedAt:new Date().toISOString(),editedFields:[] as string[]};
 if(previous){next.claims=next.claims.map(c=>previous.claims.find(v=>v.number===c.number&&v.text===c.text)||c);if(previous.title===next.title&&previous.abstract===next.abstract)next.embedding=previous.embedding;else delete next.embedding;}
 const changed=Object.keys(patch).filter(k=>k in fields&&JSON.stringify((next as unknown as Record<string,unknown>)[k])!==JSON.stringify((previous as unknown as Record<string,unknown>|undefined)?.[k]));
 if(previous&&!changed.length)return {patent:previous,dataset:dataset(datasetId)!};
 next.editedFields=[...new Set([...(previous as (typeof previous)&{editedFields?:string[]})?.editedFields||[],...changed])];
 const textChanged=previous&&(previous.description!==next.description||JSON.stringify(previous.claims.map(c=>[c.number,c.text]))!==JSON.stringify(next.claims.map(c=>[c.number,c.text])));
 db.exec('BEGIN');try{db.prepare('INSERT OR REPLACE INTO patents VALUES(?,?,?)').run(datasetId,id,JSON.stringify(next));if(textChanged)clearCheckpoints(datasetId,id);const meta=refreshDataset(datasetId);db.exec('COMMIT');return {patent:next,dataset:meta};}catch(e){db.exec('ROLLBACK');throw e;}}
export function deleteRecords(datasetId:string,ids:string[]){if(!dataset(datasetId))throw new Error('数据集不存在');if(!ids.length)throw new Error('请选择要删除的记录');const unique=[...new Set(ids)];db.exec('BEGIN');try{let deleted=0;for(const id of unique){deleted+=Number(db.prepare('DELETE FROM patents WHERE dataset_id=? AND id=?').run(datasetId,id).changes);clearCheckpoints(datasetId,id);}const meta=refreshDataset(datasetId);db.exec('COMMIT');return {deleted,dataset:meta};}catch(e){db.exec('ROLLBACK');throw e;}}
export function deleteDataset(id:string){if(!dataset(id))throw new Error('数据集不存在');db.exec('BEGIN');try{db.prepare('DELETE FROM patents WHERE dataset_id=?').run(id);db.prepare('DELETE FROM datasets WHERE id=?').run(id);db.prepare('DELETE FROM settings WHERE key=?').run('entities:'+id);clearCheckpoints(id);if(setting('active_dataset')===id){const next=datasets()[0];if(next)setting('active_dataset',next.id);else db.prepare("DELETE FROM settings WHERE key='active_dataset'").run();}db.exec('COMMIT');return {active:dataset()?.id||null};}catch(e){db.exec('ROLLBACK');throw e;}}
const indexing=new Set<string>();
const readers=new Map<string,number>();
export const isIndexing=(id:string)=>indexing.has(id);
export const isDataBusy=(id:string)=>indexing.has(id)||Boolean(readers.get(id));
export function beginDataRead(id:string){if(!dataset(id))throw new Error('数据集不存在');readers.set(id,(readers.get(id)||0)+1);}
export function endDataRead(id:string){const remaining=(readers.get(id)||1)-1;if(remaining)readers.set(id,remaining);else readers.delete(id);}
export function claimIndex(id:string){if(indexing.has(id))throw new Error('该数据集已有数据任务在运行');indexing.add(id);}
export function releaseDataJob(id:string){indexing.delete(id);}
export async function indexDataset(id:string,signal:AbortSignal,progress:(p:{done:number;total:number})=>void,request:typeof embed=embed){try{const records=analysisPatents(id),pending=records.filter(p=>!p.embedding?.length);let done=records.length-pending.length;refreshDataset(id);progress({done,total:records.length});for(let i=0;i<pending.length;i+=10){signal.throwIfAborted();const batch=pending.slice(i,i+10),vectors=await request(batch.map(p=>p.title+'\n'+p.abstract),signal);for(let j=0;j<batch.length;j++)db.prepare("UPDATE patents SET payload=json_set(payload,'$.embedding',json(?)) WHERE dataset_id=? AND id=?").run(JSON.stringify(vectors[j]),id,batch[j].id);done+=batch.length;refreshDataset(id);progress({done,total:records.length});}return refreshDataset(id);}finally{indexing.delete(id);}}
