import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import type {Patent,Params,AnalysisResult,Dataset,Row} from '@/lib/types';
import {count,wordCounts,tokens,cosine,lexical,clusters,cooperation,citationGraph,pagerank,coupling,coCitations,concentration,keywordWeights,kleinbergBursts,lifecycleFit} from './algorithms';
import {clusterMap} from './cluster-map';
import {db} from './db';
import {embed} from './model';
import {citationMainPaths,citationScreening,extractEffects,type EffectExtractor} from './substantive-analysis';
import {extractClaimElements} from './claim-analysis';
import {compareClaims} from './claim-comparison';
import {governedRecords,datasetAudit} from './research';
import type {EntityRule} from '@/lib/types';

export const TOOL_DEFS=[
 ['search_patents','专利检索','检索与读取',['title','abstract']],['read_patent_details','专利详情','检索与读取',['title']],
 ['get_dataset_summary','数据概况','数据与态势',[]],['analyze_patent_trend','公开趋势','数据与态势',['publicationDate']],['analyze_lifecycle','生命周期统计','数据与态势',['publicationDate']],['analyze_ipc_distribution','IPC分类分布','数据与态势',['ipc']],['analyze_country_distribution','记录公开局','数据与态势',[]],
 ['generate_wordcloud','关键词词频','热点与主题',['title']],['analyze_burst_terms','关键词突现','热点与主题',['publicationDate','abstract']],['analyze_yearly_keywords','年度关键词','热点与主题',['publicationDate','title']],['analyze_clustering','技术主题聚类','热点与主题',['embedding']],
 ['analyze_co_network','申请人合作网络','竞争格局',['applicants']],['analyze_competitor_evolution','竞争者演化','竞争格局',['applicants','publicationDate','ipc']],['analyze_entity_portfolio','申请人组合','竞争格局',['applicants']],['analyze_concentration','申请人集中度','竞争格局',['applicants']],
 ['analyze_tech_roadmap','引证技术主路径','技术路线',['publicationDate','citations']],['analyze_patent_valuation','引证指标筛查（非估值）','价值与机会',['publicationDate']],['analyze_tech_matrix','技术效果矩阵','价值与机会',['abstract']],
 ['analyze_citation_network','引证、共引与耦合','引证与同族',['citations']],['analyze_family_geography','同族地域','引证与同族',['familyMembers']],
 ['audit_search_strategy','检索策略审计','审计与监测',['title']],['monitor_patent_changes','数据变化监测','审计与监测',['title']],
 ['analyze_legal_status','来源时点法律状态','法律与权利要求',['legalStatus','legalAsOf']],['analyze_claim_elements','权利要求要素','法律与权利要求',['claims']],
 ['compare_claims','权利要求对照','法律与权利要求',['claims']],['audit_dataset','数据质量审计','审计与监测',[]],
] as const;
const integer=z.preprocess(v=>typeof v==='string'&&/^\d+$/.test(v)?Number(v):v,z.number().int());
export const paramsSchema=z.object({query:z.string().max(2000).optional(),top_k:integer.pipe(z.number().min(1).max(1000)).optional(),year_start:integer.optional(),year_end:integer.optional(),applicant:z.string().optional(),ipc:z.string().optional(),claim_numbers:z.array(integer.pipe(z.number().min(1))).max(1000).optional(),patent_numbers:z.array(z.string()).max(5).optional(),k:integer.pipe(z.number().min(2).max(12)).optional(),dimension:z.enum(['applicant','inventor']).optional(),strategies:z.array(z.object({name:z.string(),query:z.string()})).min(2).max(10).optional(),strategy_id:z.string().max(100).optional(),frequency:z.enum(['year','month']).optional(),counting:z.enum(['publication','family']).optional()}).strict();
export function capability(tool:string,records:Patent[]){const def=TOOL_DEFS.find(d=>d[0]===tool);if(!def)return {available:false,reason:'未知工具'};if(tool==='analyze_legal_status'&&!records.some(p=>p.legalStatus&&p.legalAsOf))return {available:false,reason:'当前数据没有同时提供状态与来源时点的记录'};const missing=def[3].filter(field=>!records.some(p=>{const v=p[field as keyof Patent];return Array.isArray(v)?v.length>0:Boolean(v);}));return {available:records.length>0&&!missing.length,reason:!records.length?'尚未导入专利':missing.length?'当前数据缺少 '+missing.join('、'):''};}
export function scope(records:Patent[],params:Params){return records.filter(p=>(!params.year_start||Number(p.publicationDate.slice(0,4))>=params.year_start)&&(!params.year_end||Number(p.publicationDate.slice(0,4))<=params.year_end)&&(!params.applicant||p.applicants.some(x=>x.toLowerCase().includes(params.applicant!.toLowerCase())))&&(!params.ipc||p.ipc.some(x=>x.startsWith(params.ipc!))));}
export type ToolContext={monitorScope?:string;entityRules?:EntityRule[];nameTopics?:(rows:Row[],records:Patent[],signal?:AbortSignal)=>Promise<Row[]>;onWork?:(done:number,total:number,label:string)=>void;semantic?:boolean;signal?:AbortSignal;queryVector?:number[];extract?:(patent:Patent)=>Promise<Row[]>;effectExtract?:EffectExtractor;onProgress?:(done:number,total:number)=>void;onCheckpoint?:(done:number,total:number,reused:number)=>void};
export async function executeTool(name:string,input:unknown,meta:Dataset,all:Patent[],ctx:ToolContext={}):Promise<AnalysisResult>{
 const params=paramsSchema.parse(input);const specific=['search_patents','read_patent_details','analyze_claim_elements','compare_claims','analyze_tech_matrix','audit_dataset'].includes(name);const normalized=specific?all:governedRecords(all,ctx.entityRules||[]).records;const inputRecords=scope(normalized,params);const governed=governedRecords(inputRecords,[],specific?'publication':params.counting);const records=governed.records,def=TOOL_DEFS.find(d=>d[0]===name);if(!def)throw new Error('工具不存在');
 const result:AnalysisResult={id:randomUUID(),tool:name,title:def[1],status:'completed',datasetId:meta.id,params,summary:'',rows:[],warnings:['结果仅代表当前导入与筛选后的语料。'],method:'描述性统计',evidence:[],createdAt:new Date().toISOString()};const cap=capability(name,records);if(!cap.available)return {...result,status:'unavailable',summary:cap.reason};
 result.scope={inputCount:inputRecords.length,analyzedCount:records.length,counting:specific?'publication':params.counting||'publication',patentIds:records.map(p=>p.id),entityRules:ctx.entityRules||[]};
 if(params.counting==='family'&&!specific)result.warnings.push(`按来源familyId去重，保留最早公开件；${governed.unknown} 条缺标识记录独立保留。代表件字段不等同于全同族信息。`);
 if(ctx.entityRules?.length)result.warnings.push('申请人按人工确认的别名规则归并；原始名称和受让人字段未改写。');
 const top=params.top_k||20;const summary=(text:string)=>result.summary=text;const evidence=(ps:Patent[])=>result.evidence.push(...ps.map(p=>p.id));
 const yearly=()=>count(records.map(p=>p.publicationDate.slice(0,4)).filter(Boolean)).sort(([a],[b])=>a.localeCompare(b));
 const rankings=(query:string)=>lexical(records,query).slice(0,top);const countRows=(values:string[],key:string)=>count(values).slice(0,top).map(([value,n])=>({[key]:value,count:n}));
 switch(name){
 case 'audit_dataset':{result.rows=datasetAudit(inputRecords);summary(`检查 ${inputRecords.length} 条记录，发现 ${result.rows.length} 项缺失或定位问题；缺失字段不表示虚假记录。`);result.method='逐记录检查字段、日期格式、重复公开编号及权利要求原文定位；不是官方真实性认证';evidence(inputRecords);break;}
 case 'compare_claims':{if(!params.patent_numbers||params.patent_numbers.length<2)throw new Error('至少提供两个公开编号，第一个作为基准');const selected=params.patent_numbers.map(id=>records.find(p=>p.id===id));if(selected.some(p=>!p?.claims.length))throw new Error('对照编号不存在或缺少权利要求，不能跳过缺失编号');result.rows=await compareClaims(meta.id,selected as Patent[],params.claim_numbers,ctx.signal,ctx.onWork);summary(`以 ${selected[0]!.id} 为基准，对照 ${selected.length-1} 项专利，保留 ${result.rows.length} 行证据。`);result.method='claim-comparison-v1：全文分段要素抽取、逐项语义对照、原文证据索引定位；保留相同、部分重合及未发现三类结果';result.warnings.push('未发现仅限指定权利要求，不代表整篇说明书或全球现有技术不存在该特征；不是侵权、新颖性或FTO结论。');evidence(selected as Patent[]);break;}
 case 'search_patents':{
  if(!params.query?.trim())throw new Error('请输入检索问题');let ranked=rankings(params.query);if(ctx.semantic){if(records.some(p=>!p.embedding))throw new Error('语义索引未完成，请在数据页建立索引');const vector=ctx.queryVector||(await embed([params.query],ctx.signal))[0];ranked=records.map(p=>({p,score:cosine(vector,p.embedding!)})).sort((a,b)=>b.score-a.score).slice(0,top);result.method='text-embedding-v4 余弦相似度；Top-K 相关性筛查，不是全库命中数';}else result.method='BM25（k1=1.2，b=0.75）标题与摘要词法检索；排除零相关度记录';
  result.rows=ranked.map(({p,score})=>({patent:p.id,title:p.title,applicants:p.applicants.join('; '),year:p.publicationDate.slice(0,4),score:Number(score.toFixed(4))}));evidence(ranked.map(r=>r.p));summary(`返回 ${ranked.length} 条筛查结果。`);break;
 }
 case 'read_patent_details':{if(!params.patent_numbers?.length)throw new Error('请提供 patent_numbers 公开编号');const selected=records.filter(p=>params.patent_numbers!.includes(p.id));result.rows=selected.map(p=>({patent:p.id,title:p.title,abstract:p.abstract,applicants:p.applicants,assignees:p.assignees,publicationDate:p.publicationDate,ipc:p.ipc,cpc:p.cpc,claims:p.claims,description:p.description,public_evidence:p.publicEvidence,source:p.sourceUrl}));evidence(selected);summary(`读取 ${selected.length} 条原始记录；未找到的编号不会补造。`);break;}
 case 'get_dataset_summary':{result.rows=[{records:records.length,period:yearly().map(([year])=>year).join(' / '),applicants:new Set(records.flatMap(p=>p.applicants)).size,indexed:records.filter(p=>p.embedding).length},...Object.keys(meta.coverage).map(field=>({field,coverage:records.filter(p=>{const value=p[field as keyof Patent];return Array.isArray(value)?value.length>0:Boolean(value);}).length/records.length}))];summary(`当前语料 ${records.length} 条真实记录。`);result.warnings.push(...meta.warnings);break;}
 case 'analyze_patent_trend':{const monthly=params.frequency==='month';result.rows=count(records.map(p=>p.publicationDate.slice(0,monthly?7:4))).map(([period,n])=>({period,count:n})).sort((a,b)=>String(a.period).localeCompare(String(b.period)));result.chart={kind:'line',x:'period',y:'count'};summary(`按公开日期统计 ${result.rows.length} 个时间点。`);result.warnings.push('抽样和缺失月份会影响趋势；不得解释为行业总量。');evidence(records);break;}
 case 'analyze_lifecycle':{const fitted=lifecycleFit(records);result.rows=fitted.points;result.chart={kind:'line',x:'year',y:'cumulative'};result.method='logistic-fit-v1：L/(1+exp(-k*(year-t0)))非线性最小二乘，150轮坐标优化；至少6个公开年。';if(fitted.fit){result.rows.push({type:'fit_diagnostics',...fitted.fit});summary('已拟合样本累计公开曲线，输出参数、R²、RMSE与残差。');if(fitted.fit.weakly_identified)result.warnings.push('拐点超出观测范围或渐近上限接近搜索边界，参数识别不足。');}else summary('不足6个公开年，保留年度统计，不强行拟合生命周期。');result.warnings.push('非随机样本及缺失年份限制曲线解释；拟合成功不证明行业成熟、衰退或未来增长。');evidence(records);break;}
 case 'analyze_ipc_distribution':{result.rows=countRows(records.flatMap(p=>[...new Set(p.ipc.map(code=>code.slice(0,4)))]),'ipc');result.chart={kind:'bar',x:'ipc',y:'count'};summary(`识别 ${result.rows.length} 个 IPC 小类，CPC 未混入。`);evidence(records.filter(p=>p.ipc.length));break;}
 case 'analyze_country_distribution':{result.rows=countRows(records.map(p=>p.id.slice(0,2)),'office');result.chart={kind:'bar',x:'office',y:'count'};summary('统计记录公开局；缺少最早同族公开时点，不能判定首次公开局、市场覆盖或有效权利地域。');break;}
 case 'generate_wordcloud':{result.rows=keywordWeights(records).slice(0,params.top_k||50);result.chart={kind:'bar',x:'word',y:'tfidf'};result.method='词频TF、文档频率DF与平滑TF-IDF=(1+ln TF)*(1+ln((N+1)/(DF+1)))；去停用词';summary('按TF-IDF提取语料关键词，同时保留原始TF和DF。');break;}
 case 'analyze_yearly_keywords':{result.rows=yearly().flatMap(([year])=>keywordWeights(records.filter(p=>p.publicationDate.startsWith(year)),records).slice(0,params.top_k||10).map(row=>({year,...row})));result.chart={kind:'bar',x:'word',y:'tfidf'};result.method='年度词频×整个筛选语料的平滑逆文档频率';summary('计算年度TF-IDF关键词，并保留年度文档频率。');break;}
 case 'analyze_burst_terms':{if(yearly().length<2)return {...result,status:'unavailable',summary:'至少需要两个公开年才能识别突现'};result.rows=kleinbergBursts(records,(done,total)=>ctx.onWork?.(done,total,'词项突现模型')).slice(0,top);result.method='Kleinberg batched-arrival：二项发射概率、s=2、gamma=1，上升状态惩罚gamma*ln(N)，Viterbi最优状态路径与分层突现区间；不是占比提升替代。https://www.cs.cornell.edu/info/people/kleinber/bhs.pdf';summary(`识别 ${result.rows.length} 个词项突现区间，零区间是有效结果。`);result.warnings.push('只对有记录的公开年构建批次；缺失年份未填造记录。突现仅描述样本词项变化。');break;}
 case 'analyze_clustering':{result.rows=clusters(records,params.k||6);if(ctx.nameTopics){ctx.onWork?.(0,result.rows.length,'归纳技术主题');try{result.rows=await ctx.nameTopics(result.rows,records,ctx.signal);ctx.onWork?.(result.rows.length,result.rows.length,'归纳技术主题');}catch(e){if(ctx.signal?.aborted)throw e;result.warnings.push('主题命名未完成：'+(e as Error).message+'；保留聚类与关键词，可重新运行。');}}result.clusterMap=clusterMap(records,result.rows);result.chart={kind:'bar',x:result.rows.some(row=>row.topic_name)?'topic_name':'keywords',y:'count'};result.method='1024维文本嵌入、余弦距离 K-means、固定种子42，最多30轮；主题关键词按全库参照TF-IDF提取。散点坐标为单位化嵌入的二维PCA投影；聚类在原始高维空间计算，二维距离不是完整语义距离。';summary(`生成 ${result.rows.length} 个技术主题；标签需人工复核。`);evidence(records);break;}
 case 'analyze_co_network':{result.graph=cooperation(records,params.dimension);result.rows=result.graph.edges.map(e=>({...e}));summary(`合作网络 ${result.graph.nodes.length} 个实体、${result.graph.edges.length} 条边。`);result.method='同一条专利中的同角色实体共现；申请人与受让人不混合';if(!result.graph.edges.length)result.warnings.push('语料中没有多申请人记录，网络没有合作边。');evidence(records);break;}
 case 'analyze_entity_portfolio':{result.rows=count(records.flatMap(p=>[...new Set(p.applicants)])).slice(0,top).map(([applicant,n])=>({applicant,count:n,ipc:count(records.filter(p=>p.applicants.includes(applicant)).flatMap(p=>p.ipc.map(x=>x.slice(0,4)))).slice(0,3).map(([code])=>code).join(', ')}));result.chart={kind:'bar',x:'applicant',y:'count'};summary(`返回 ${result.rows.length} 个申请人；未做母子公司集团归并。`);evidence(records);break;}
 case 'analyze_concentration':{result.rows=[concentration(records)];summary('计算 CR3、CR5、CR10、HHI 和有效主体数。');result.method='多申请人专利分数计数；专利份额不是市场份额';evidence(records);break;}
 case 'analyze_competitor_evolution':{const selected=count(records.flatMap(p=>p.applicants)).slice(0,top).map(([name])=>name);result.rows=selected.flatMap(applicant=>yearly().map(([year])=>({applicant,year,count:records.filter(p=>p.publicationDate.startsWith(year)&&p.applicants.includes(applicant)).length,ipc:count(records.filter(p=>p.publicationDate.startsWith(year)&&p.applicants.includes(applicant)).flatMap(p=>p.ipc.map(x=>x.slice(0,4)))).slice(0,3).map(([code])=>code).join(', ')})));summary('展示主要申请人的年度公开量与 IPC 布局。');evidence(records);break;}
 case 'analyze_tech_roadmap':{
  const analysis=citationMainPaths(records);result.rows=analysis.rows;result.graph=analysis.graph;
  result.method='citation-main-path-v1：真实内部引证反向为早期→后期；SPC=源到起点路径数×终点到汇路径数；每个连通分量以动态规划选择SPC总和最大的源—汇路径。https://arxiv.org/abs/cs/0309023';
  if(!analysis.rows.length){result.status='unavailable';summary('没有可按公开日期确认顺序的内部引证，无法计算引证主路径。');}else summary(`实际计算 ${analysis.rows.length} 条引证的路径权重，识别 ${analysis.paths.length} 条分量主路径；覆盖 ${analysis.connected}/${records.length} 条专利。`);
  result.warnings.push(`排除 ${analysis.rejected} 条自引、日期缺失或公开时序不一致的内部边；同日边也不用于时间路线。`,`样本引证主路径不是完整行业路线，也不证明技术继承或因果关系。`);evidence(records.filter(p=>analysis.graph.nodes.some(n=>n.id===p.id)));break;
 }
 case 'analyze_patent_valuation':{
  result.rows=citationScreening(records).slice(0,top);result.method='citation-pareto-v1：真实内部被引数与内部引证PageRank（阻尼0.85、40轮）的非支配分层，不使用加权总分；同层按公开编号排列，不声明层内高低。';
  const deals=records.flatMap(p=>p.publicEvidence?.commercialContext?[{patent:p.id,type:'相关知识产权组合交易（非单项专利价格）',...p.publicEvidence.commercialContext,economic_value:null}]:[]);result.rows.push(...deals);if(deals.length)result.warnings.push('披露金额针对组合交易和许可买断，不能作为本专利价格或分摊到其他专利。');const ownership=records.flatMap(p=>(p.publicEvidence?.legalEvents||[]).filter(e=>/assignment|change of name|merger/i.test(e.title)).map(e=>({patent:p.id,type:'登记权属事件（非成交价）',event_date:e.date,event:e.title,details:e.details,source:p.publicEvidence!.sourceUrl,economic_value:null})));result.rows.push(...ownership);summary(`已计算 ${records.length} 条记录的引证指标与非支配层，返回 ${Math.min(top,records.length)} 条筛查结果。附加 ${ownership.length} 条权属事件与 ${deals.length} 条组合交易背景；未提供单项专利成交金额，economic_value 留空。`);
  result.warnings.push('商业价值评估未执行：当前接口没有收益、交易及维护成本资料，当前样本还缺少官方核验的法律状态、完整同族和全库前向引证。','Pareto层仅按两个样本引证指标筛查；不是价值等级。引证缺失不代表没有引用，权利要求数量不作为质量加分。');evidence(records);break;
 }
 case 'analyze_tech_matrix':{
  const selected=params.patent_numbers?.length?records.filter(p=>params.patent_numbers!.includes(p.id)):records;
  if(!selected.length)return {...result,status:'unavailable',summary:'指定编号不在当前分析范围中'};
  let checkpoint={done:0,total:0,reused:0};result.rows=await extractEffects(meta.id,selected,ctx.signal,ctx.effectExtract,ctx.onProgress,{onCheckpoint:(done,total,reused)=>{checkpoint={done,total,reused};ctx.onCheckpoint?.(done,total,reused);}});
  result.method='full-text-evidence-v3：Qwen逐段读取全部摘要、权利要求与说明书（含背景/概要；16000字符分段、1000字符重叠），按原文片段编号抽取明确措施—效果关系；程序取回并校验连续引文。每段成功后立即保存断点，停止或失败后以相同参数重跑会跳过已完成分段。';
  summary(`完成 ${selected.length} 条专利全文读取，保留 ${result.rows.length} 条可定位的技术—效果关系；${checkpoint.total} 个分段中复用 ${checkpoint.reused} 段、新执行 ${checkpoint.done-checkpoint.reused} 段。没有明确陈述则不补造。`);
  result.warnings.push('标签由模型按原文生成，不用预设词表；相似标签尚未人工归并。','关系是专利文本中的声明，逐字校验只确认出处，不代替专家核验或独立实验验证。');evidence(selected);break;
 }
 case 'analyze_citation_network':{result.graph=citationGraph(records);const ranks=pagerank(result.graph),internal=new Set(records.map(p=>p.id));result.rows=[{metric:'内部引证边',count:result.graph.edges.filter(e=>internal.has(e.target)).length},{metric:'外部引证边',count:result.graph.edges.filter(e=>!internal.has(e.target)).length},...result.graph.nodes.filter(n=>internal.has(n.id)).sort((a,b)=>ranks.get(b.id)!-ranks.get(a.id)!).slice(0,top).map(n=>({patent:n.id,pagerank:ranks.get(n.id)})),...coupling(records).map(r=>({type:'bibliographic_coupling',...r})),...coCitations(records).map(r=>({type:'co_citation',...r}))];result.method='实际后向引证有向图、PageRank阻尼0.85（40轮）、共引和文献耦合';summary(`引证图 ${result.graph.nodes.length} 个节点、${result.graph.edges.length} 条真实来源边。`);result.warnings.push('外部节点未提供全文；缺少全库前向被引信息，不能据此评价行业影响力。');evidence(records);break;}
 case 'analyze_family_geography':{const selected=records.filter(p=>p.familyMembers.length),members=[...new Set(selected.flatMap(p=>p.familyMembers))];result.rows=[...countRows(members.map(x=>x.slice(0,2)),'family_office'),...selected.flatMap(p=>p.familyMembers.map(member=>({patent:p.id,member,office:member.slice(0,2),family_definition:p.publicEvidence?.familyDefinition||'来源提供的同族成员',source:p.publicEvidence?.sourceUrl||p.sourceUrl,observed_at:p.publicEvidence?.retrievedAt||''})))];summary(`当前 ${selected.length}/${records.length} 条记录有同族资料，统计 ${members.length} 个去重的代表公开件；缺失记录不当作零同族。`);result.warnings.push('Google补充资料仅含Family Applications及Country Status中申请/公开局代表公开件，不是完整全球同族或全部公开版本。','同族公开局不等于当前有效权利地域。');evidence(selected);break;}
 case 'audit_search_strategy':{if(!params.strategies)throw new Error('请提供至少两版 strategies（name 与 query）');const sets=params.strategies.map(s=>new Set(rankings(s.query).map(r=>r.p.id)));result.rows=params.strategies.map((s,i)=>{const previous=sets[i-1]||new Set(),others=new Set(sets.flatMap((set,j)=>j===i?[]:[...set]));return {name:s.name,query:s.query,returned:sets[i].size,unique:[...sets[i]].filter(id=>!others.has(id)).length,added:[...sets[i]].filter(id=>!previous.has(id)).length,removed:[...previous].filter(id=>!sets[i].has(id)).length,patents:[...sets[i]]};});summary('对比BM25 Top-K 返回集；这不是查全率评估。');break;}
 case 'monitor_patent_changes':{if(!params.query||!params.strategy_id)throw new Error('请提供 query 与 strategy_id');const current=rankings(params.query).map(r=>{const {embedding,rawText,locations,...record}=r.p;return record;});const key=JSON.stringify([meta.id,params.strategy_id,params.query,ctx.monitorScope||'dataset',{year_start:params.year_start,year_end:params.year_end,applicant:params.applicant,ipc:params.ipc,top:params.top_k||20,counting:params.counting||'publication'}]);const old=db.prepare('SELECT payload FROM monitors WHERE key=?').get(key) as {payload:string}|undefined;const previous:typeof current=old?JSON.parse(old.payload):[];const prior=new Map(previous.map(p=>[p.id,JSON.stringify(p)])),now=new Map(current.map(p=>[p.id,JSON.stringify(p)]));result.rows=[...current.filter(p=>!prior.has(p.id)).map(p=>({patent:p.id,change:old?'新增':'基线收录'})),...current.filter(p=>prior.has(p.id)&&prior.get(p.id)!==JSON.stringify(p)).map(p=>({patent:p.id,change:'记录变化'})),...previous.filter(p=>!now.has(p.id)).map(p=>({patent:p.id,change:'移出返回集'}))];db.prepare('INSERT OR REPLACE INTO monitors VALUES(?,?)').run(key,JSON.stringify(current));result.warnings.push('比较全部规范字段，排除向量、原文副本和位置偏移；研究范围与筛选参数独立建立基线，不互相比作新增或移除。');summary(old?`对比已保存的返回集基线：${result.rows.length} 个变化事件。`:`已建立当前数据集的检索基线，收录 ${current.length} 条记录；首次运行不表示新增专利。`);result.warnings.push('首次运行是基线初始化；监测仅比较已导入数据，不代表互联网新增专利。');break;}
 case 'analyze_legal_status':{const selected=records.filter(p=>p.legalStatus&&p.legalAsOf);result.rows=[...countRows(selected.map(p=>p.legalStatus),'status'),...selected.map(p=>({patent:p.id,status:p.legalStatus,as_of:p.legalAsOf,basis:p.publicEvidence?.statusBasis||'来源时点声明',source:p.publicEvidence?.sourceUrl||p.sourceUrl})),...selected.flatMap(p=>(p.publicEvidence?.legalEvents||[]).map(e=>({patent:p.id,event_date:e.date,code:e.code,event:e.title,details:e.details,source:p.publicEvidence!.sourceUrl})))];summary(`统计 ${selected.length}/${records.length} 条有时点来源声明的记录，其余状态未知；保留原文法律事件。`);result.method='来源状态声明分布与逐条法律事件读取；Google状态仅为第三方推定，as_of是获取时点，不是官方核验时点';result.warnings.push('Google明确声明未做法律分析、不保证状态准确；不能表述为官方有效性确认。','获取日期、事件发生日期和未来预计到期日期分别记录，不以预计到期推断当前有效性。');evidence(selected);break;}
 case 'analyze_claim_elements':{
  const selected=params.patent_numbers?.length?records.filter(p=>params.patent_numbers!.includes(p.id)&&p.claims.length):records.filter(p=>p.claims.length).slice(0,1);if(!selected.length)throw new Error('指定专利没有可用权利要求');
  result.rows=ctx.extract?await ctx.extract(selected[0]):await extractClaimElements(meta.id,selected,params.claim_numbers,ctx.signal,ctx.onWork);
  result.rows=result.rows.map(row=>{const patent=selected.find(p=>p.id===(row.patent||selected[0].id))!;const claim=patent?.claims.find(c=>c.number===row.claim);if(!claim||typeof row.quote!=='string'||!row.quote.trim()||!claim.text.includes(row.quote))throw new Error('模型抽取的引文不能定位到权利要求原文');return {...row,patent:patent.id,claim_offset:row.claim_offset??claim.text.indexOf(row.quote)};});
  result.method='claim-evidence-v2：按原文片段编号辅助拆解全部指定权利要求与技术关联；逐字定位引文、每段保存断点；claim_numbers可显式选择，不限制前三项或8个要素。';summary(`分析 ${selected.length} 条专利的 ${selected.reduce((n,p)=>n+p.claims.filter(c=>!params.claim_numbers||params.claim_numbers.includes(c.number)).length,0)} 项权利要求，提取 ${result.rows.length} 个可定位要素。`);result.warnings.push('模型辅助抽取需要人工复核；这不是权利范围解释、侵权判断或FTO意见。');evidence(selected);break;
 }
 }
 if(ctx.signal?.aborted)throw new Error('任务已停止');return result;
}
