import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
process.env.PATENT_DATA_DIR=mkdtempSync(join(tmpdir(),'atlas-analysis-loading-'));
const {analysisPatents,patent,patentPage,saveDataset}=await import('../src/server/db');
const {normalize,datasetMeta}=await import('../src/server/importers');
const {executeTool}=await import('../src/server/tools');
const {toolDefaults}=await import('../src/server/planning');
const {extractEffects}=await import('../src/server/substantive-analysis');
function setup(){const raw='A ledger stores authenticated events.';const records=Array.from({length:25},(_,i)=>normalize({id:'US'+(8000+i)+'A1',title:'Ledger '+i,abstract:'Authenticated events',applicants:['Example Institute'],publicationDate:'2020-01-01',description:raw,rawText:raw,claims:[{number:1,text:raw,sourceStart:0,sourceEnd:raw.length}],embedding:Array(1024).fill(.1)},'Test fixture'));for(const p of records)p.embedding=Array(1024).fill(.1);const meta=datasetMeta('Fixture',records,'https://example.com','Algorithm fixture');saveDataset(meta,records);return {meta,records};}
test('analysis projection omits full text without losing coverage, claims, vectors or default IDs',async()=>{
 const {meta,records}=setup(),light=analysisPatents(meta.id);assert.equal(light.length,25);assert.equal(light[0].rawText,'');assert.equal(light[0].description,'');assert.equal(light[0].deferredText?.descriptionChars,records[0].description.length);assert.deepEqual(light[0].claims,records[0].claims);assert.deepEqual(light[0].embedding,records[0].embedding);assert.deepEqual(toolDefaults('compare_claims',light),toolDefaults('compare_claims',records));
 for(const tool of ['get_dataset_summary','audit_dataset','read_patent_details','monitor_patent_changes']){const params=tool==='read_patent_details'?{patent_numbers:[records[0].id]}:tool==='monitor_patent_changes'?{query:'ledger',strategy_id:'fixture'}:{};const full=await executeTool(tool,params,meta,records,{monitorScope:tool==='monitor_patent_changes'?'full':undefined}),projected=await executeTool(tool,params,meta,light,{monitorScope:tool==='monitor_patent_changes'?'light':undefined});assert.deepEqual(projected.rows,full.rows,tool);}
 assert.deepEqual(patent(meta.id,records[0].id),JSON.parse(JSON.stringify(records[0])));
});
test('list returns one page and literal text search; details retain full source',()=>{const {meta,records}=setup();const first=patentPage(meta.id,'',1),second=patentPage(meta.id,'',2);assert.equal(first.total,25);assert.equal(first.records.length,20);assert.equal(second.records.length,5);assert.equal(first.records[0].rawText,undefined);assert.equal(first.records[0].embedding,undefined);assert.equal(first.records[0].claimCount,1);assert.equal(first.records[0].descriptionChars,records[0].description.length);assert.equal(patentPage(meta.id,'Example Institute',1).total,25);assert.equal(patentPage(meta.id,'not found',1).total,0);});
test('effect extraction reads real full text only for selected projected records',async()=>{const {meta,records}=setup();let seen=false;const rows=await extractEffects(meta.id,analysisPatents(meta.id).slice(0,1),undefined,async text=>{if(text.includes(records[0].description))seen=true;return [];},undefined,{cache:false});assert.equal(seen,true);assert.deepEqual(rows,[]);});
test('list search still matches titles and IDs when applicant is missing',()=>{const p=normalize({id:'US9999A1',title:'Missing applicant ledger'},'Fixture'),meta=datasetMeta('Missing',[p],'https://example.com','Fixture');saveDataset(meta,[p]);assert.equal(patentPage(meta.id,'ledger',1).total,1);assert.equal(patentPage(meta.id,'US9999',1).total,1);});
test('analysis cache follows edits, vector changes and deletion without changing full text',async()=>{const {meta,records}=setup();const {db}=await import('../src/server/db');analysisPatents(meta.id);db.prepare("UPDATE patents SET payload=json_set(payload,'$.description',?,'$.title',?,'$.embedding',json(?)) WHERE dataset_id=? AND id=?").run('Changed source text','New ledger',JSON.stringify(Array(1024).fill(.2)),meta.id,records[0].id);const updated=analysisPatents(meta.id)[0];assert.equal(updated.title,'New ledger');assert.equal(updated.deferredText?.descriptionChars,'Changed source text'.length);assert.equal(updated.embedding?.[0],.2);assert.equal(patent(meta.id,updated.id)?.rawText,records[0].rawText);db.prepare('DELETE FROM patents WHERE dataset_id=? AND id=?').run(meta.id,updated.id);assert.equal(analysisPatents(meta.id).length,24);assert.equal(patentPage(meta.id,'New ledger',1).total,0);});
