import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import type {Run} from '../src/lib/types';
process.env.PATENT_DATA_DIR=mkdtempSync(join(tmpdir(),'patent-records-'));
const {db,saveDataset,patents,dataset,newConversation,saveReport,reports,setting}=await import('../src/server/db');
const {normalize,datasetMeta}=await import('../src/server/importers');
const {writeRecord,deleteRecords,deleteDataset,indexDataset,claimIndex,isIndexing,isDataBusy,beginDataRead,endDataRead}=await import('../src/server/data-management');
function setup(n=1){const records=Array.from({length:n},(_,i)=>normalize({id:'US'+(100+i)+'A1',title:'Original title '+i,abstract:'Ledger record',publicationDate:'2020-01-01',claims:[{number:1,text:'A processor.',sourceStart:0,sourceEnd:12}],description:'Original description'},'Test fixture'));const meta=datasetMeta('Test fixture',records,'https://example.com','Algorithm test only');saveDataset(meta,records);return meta;}
test('CRUD updates counts and years; duplicates reject; partial edits preserve other fields and claim positions',async()=>{const meta=setup();const id=patents(meta.id)[0].id;writeRecord(meta.id,{id:'US200A1',title:'New title',publicationDate:'2023-01-01'});assert.equal(dataset(meta.id)!.count,2);assert.deepEqual(dataset(meta.id)!.years,['2020','2023']);assert.throws(()=>writeRecord(meta.id,{id:'US200A1',title:'Duplicate'}),/已存在/);writeRecord(meta.id,{title:'Edited'},id);assert.equal(patents(meta.id).find(p=>p.id===id)!.abstract,'Ledger record');assert.equal(patents(meta.id).find(p=>p.id===id)!.claims[0].sourceStart,0);assert.equal(deleteRecords(meta.id,[id,id]).deleted,1);assert.equal(dataset(meta.id)!.count,1);deleteRecords(meta.id,['US200A1']);assert.equal(dataset(meta.id)!.count,0);assert.deepEqual(dataset(meta.id)!.years,[]);});
test('index emits batches, resumes after failure, and text edits invalidate only their old embedding',async()=>{const meta=setup(12);claimIndex(meta.id);let calls=0;const progress:number[]=[];await assert.rejects(indexDataset(meta.id,new AbortController().signal,p=>progress.push(p.done),async texts=>{if(++calls===2)throw Error('model outage');return texts.map(()=>Array(1024).fill(.1));}),/model outage/);assert.deepEqual(progress,[0,10]);assert.equal(dataset(meta.id)!.indexed,10);assert.equal(isIndexing(meta.id),false);claimIndex(meta.id);await indexDataset(meta.id,new AbortController().signal,()=>{},async texts=>{assert.equal(texts.length,2);return texts.map(()=>Array(1024).fill(.2));});assert.equal(dataset(meta.id)!.indexed,12);const p=patents(meta.id)[0];writeRecord(meta.id,{applicants:['Updated']},p.id);assert.equal(dataset(meta.id)!.indexed,12);writeRecord(meta.id,{abstract:'Changed text'},p.id);assert.equal(dataset(meta.id)!.indexed,11);assert.equal(patents(meta.id)[0].embedding,undefined);});
test('whole dataset deletion retains reports and conversations and selects another active dataset',()=>{const meta=setup(),other=setup(),c=newConversation(meta.id);const run={id:'r',conversationId:c.id,datasetId:meta.id,question:'Snapshot',status:'completed',results:[],plan:[],answer:'Historical report',error:'',model:'Test',createdAt:new Date().toISOString(),datasetSnapshot:meta} as Run;saveReport(run,'Saved');setting('active_dataset',meta.id);deleteDataset(meta.id);assert.equal(dataset(meta.id),undefined);assert.equal(patents(meta.id).length,0);assert.ok(db.prepare('SELECT id FROM conversations WHERE id=?').get(c.id));assert.equal(reports()[0].run.answer,'Historical report');assert.equal(reports()[0].run.datasetSnapshot?.count,1);assert.equal(setting('active_dataset'),other.id);});
test('index cancellation releases the lock and does not mark missing vectors complete',async()=>{const meta=setup();const control=new AbortController();control.abort();claimIndex(meta.id);await assert.rejects(indexDataset(meta.id,control.signal,()=>{}),{name:'AbortError'});assert.equal(isIndexing(meta.id),false);assert.equal(dataset(meta.id)!.indexed,0);});
test('saving unchanged content preserves source claim positions and does not create a false edit event',()=>{const meta=setup(),p=patents(meta.id)[0];writeRecord(meta.id,{id:p.id,title:p.title,claims:p.claims.map(c=>({number:c.number,text:c.text}))},p.id);assert.deepEqual(patents(meta.id)[0],p);});
test('parallel direct tool requests keep data busy until the last read ends',()=>{const meta=setup();beginDataRead(meta.id);beginDataRead(meta.id);endDataRead(meta.id);assert.equal(isDataBusy(meta.id),true);endDataRead(meta.id);assert.equal(isDataBusy(meta.id),false);});
