import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {parseGoogleEvidence,enrichPatent} from '../src/server/public-enrichment';
import {normalize} from '../src/server/importers';
const html='<meta name="DC.relation" content="US:999" scheme="references"><dd itemprop="publicationNumber">US123B1</dd><dd itemprop="legalStatusIfi"><span itemprop="status">Expired - Fee Related</span></dd><section itemprop="family"><h1>Family</h1><h2>ID=123</h2><h2>Family Applications (1)</h2><table><tr itemprop="applications"><span itemprop="applicationNumber">US12/345</span><span itemprop="representativePublication">US123B1</span><span itemprop="ifiStatus">Expired</span></tr></table><tr itemprop="forwardReferencesOrig"><span itemprop="publicationNumber">JP999B2</span></tr></section><tr itemprop="legalEvents"><time itemprop="date" datetime="2020-01-01"></time><td itemprop="code">AS</td><td itemprop="title">Assignment</td><p itemprop="attributes">Owner name: A &amp; B</p></tr>';
test('public number is matched, citations do not become family members, observed date stays separate',()=>{const parsed=parseGoogleEvidence(html,'US123B1','2026-10-09T01:00:00Z');assert.equal(parsed.status,'Expired - Fee Related');assert.deepEqual(parsed.evidence.familyApplications.map(x=>x.publication),['US123B1']);assert.equal(parsed.evidence.legalEvents[0].date,'2020-01-01');assert.equal(parsed.evidence.legalEvents[0].details,'Owner name: A & B');const original=normalize({id:'US123B1',title:'Source title',applicants:['Original Applicant'],rawText:'Original full text'},'Source');const p=enrichPatent(original,html,'2026-10-09T01:00:00Z');assert.equal(p.legalAsOf,'2026-10-09');assert.deepEqual(p.applicants,original.applicants);assert.equal(p.rawText,original.rawText);assert.equal(original.legalStatus,'');assert.throws(()=>parseGoogleEvidence(html,'US456B1','2026-10-09'),/不匹配/);});
test('missing status or family fields remain missing; truncated family does not silently pass',()=>{const empty=parseGoogleEvidence('<dd itemprop="publicationNumber">US123B1</dd>','US123B1','2026-10-09');assert.equal(empty.status,'');assert.deepEqual(empty.evidence.familyApplications,[]);assert.throws(()=>parseGoogleEvidence(html.replace('Family Applications (1)','Family Applications (2)'),'US123B1','2026-10-09'),/不完整/);});
test('cached real pages have literal support for every family document and legal event',{skip:!existsSync('data/sources/public-enrichment/manifest.json')?'Run optional public enrichment to verify cached pages':false},()=>{const manifest=JSON.parse(readFileSync('data/sources/public-enrichment/manifest.json','utf8'));for(const id of manifest.selected){const {html,retrievedAt}=JSON.parse(readFileSync(`data/sources/public-enrichment/${id}.json`,'utf8'));const parsed=parseGoogleEvidence(html,id,retrievedAt);assert.equal(parsed.evidence.retrievedAt,retrievedAt);const table=/<h2>Family Applications[\s\S]*?<\/table>/.exec(html)![0];for(const member of parsed.evidence.familyApplications)assert.ok(table.includes(member.publication));for(const event of parsed.evidence.legalEvents){const block=html.slice(event.htmlStart,html.indexOf('</tr>',event.htmlStart)+5);assert.ok(block.includes(event.code));assert.ok(block.includes(event.date));assert.ok(block.includes(event.title));}}});
