import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
process.env.PATENT_DATA_DIR=mkdtempSync(join(tmpdir(),'patent-tools-test-'));
const {executeTool,TOOL_DEFS,paramsSchema}=await import('../src/server/tools');
const {normalize,datasetMeta,importText}=await import('../src/server/importers');
const {clusters,citationGraph,pagerank,concentration}=await import('../src/server/algorithms');
// These small invented fixtures exercise algorithms only. They are never imported into the app.
const fixtures=[0,1,2].map(i=>({...normalize({id:`US${900+i}B1`,title:`Blockchain authentication ${i}`,abstract:'Encrypted transaction security privacy',applicants:i===0?['Alpha','Beta']:['Alpha'],assignees:['Different owner'],publication_date:`202${i}-01-01`,ipc:['G06F16/00'],cpc:['H04L9/32'],claims:[{number:1,text:'A method comprising verifying a transaction.'}],description:'Test fixture description',citations:i===0?['US901','US999']:['US999'],family_members:['US900B1','EP900A1'],legal_status:'Granted',legal_status_as_of:'2025-01-01'},'UNIT TEST ONLY'),embedding:i===2?[0,1]:[1,0]}));
const meta=datasetMeta('UNIT TEST ONLY',fixtures,'test','test only');
const parameters:Record<string,object>={search_patents:{query:'blockchain',top_k:2},read_patent_details:{patent_numbers:['US900B1']},audit_search_strategy:{strategies:[{name:'a',query:'blockchain'},{name:'b',query:'authentication'}]},monitor_patent_changes:{query:'blockchain',strategy_id:'unit-test'}};
for(const [name] of TOOL_DEFS){
 if(name==='compare_claims')continue; // Evidence matching is covered with a model stub in claim-comparison.test.ts and real-model acceptance.
 test(`${name}: valid input and empty scope`,async()=>{
  const ctx={extract:async()=>[{patent:'US900B1',claim:1,element:'验证',quote:'verifying a transaction',claim_offset:20}],effectExtract:async()=>[]};
  const result=await executeTool(name,parameters[name]||{},meta,fixtures,ctx);
  assert.equal(result.status,name==='analyze_tech_roadmap'?'unavailable':'completed');assert.equal(result.datasetId,meta.id);assert.ok(result.method);assert.ok(Array.isArray(result.rows));
  const empty=await executeTool(name,{...parameters[name],year_start:2099},meta,fixtures,ctx);assert.equal(empty.status,'unavailable');assert.equal(empty.rows.length,0);
 });
}
test('zero changes are valid, not failure',async()=>{const params={query:'blockchain',strategy_id:'stable-monitor'};await executeTool('monitor_patent_changes',params,meta,fixtures);const r=await executeTool('monitor_patent_changes',params,meta,fixtures);assert.equal(r.status,'completed');assert.equal(r.rows.length,0);});
test('different research scopes and filters establish independent monitor baselines',async()=>{const params={query:'blockchain',strategy_id:'research-scope-test'};await executeTool('monitor_patent_changes',params,meta,fixtures,{monitorScope:'dataset'});const scoped=await executeTool('monitor_patent_changes',params,meta,fixtures.slice(0,1),{monitorScope:'search:authentication'});assert.ok(scoped.rows.every(row=>row.change==='基线收录'));const filtered=await executeTool('monitor_patent_changes',{...params,year_start:2022},meta,fixtures);assert.ok(filtered.rows.every(row=>row.change==='基线收录'));});
test('canonical applicant filter runs after confirmed alias normalization',async()=>{const result=await executeTool('analyze_entity_portfolio',{applicant:'Confirmed name'},meta,fixtures,{entityRules:[{alias:'Alpha',canonical:'Confirmed name',basis:'UNIT TEST ONLY'}]});assert.equal(result.status,'completed');assert.ok(result.rows.some(row=>row.applicant==='Confirmed name'));const raw=await executeTool('read_patent_details',{patent_numbers:['US900B1']},meta,fixtures,{entityRules:[{alias:'Alpha',canonical:'Confirmed name',basis:'UNIT TEST ONLY'}]});assert.ok((raw.rows[0].applicants as string[]).includes('Alpha'));});
test('monitor baselines belong to a dataset and initial records are not new patents',async()=>{const params={query:'blockchain',strategy_id:'dataset-isolation'};const first=await executeTool('monitor_patent_changes',params,{...meta,id:'monitor-source-a'},fixtures);const second=await executeTool('monitor_patent_changes',params,{...meta,id:'monitor-source-b'},fixtures);assert.ok(first.rows.every(r=>r.change==='基线收录'));assert.equal(second.rows.length,first.rows.length);assert.match(second.summary,/首次运行不表示新增专利/);const repeated=await executeTool('monitor_patent_changes',params,{...meta,id:'monitor-source-b'},fixtures);assert.equal(repeated.rows.length,0);});
test('monitor detects claim and classification changes, not only titles',async()=>{const params={query:'blockchain',strategy_id:'all-fields'};await executeTool('monitor_patent_changes',params,meta,fixtures);const changed=fixtures.map((p,i)=>i===0?{...p,ipc:['H04L9/00'],claims:[{number:1,text:'Changed actual claim.'}]}:p);const r=await executeTool('monitor_patent_changes',params,meta,changed);assert.deepEqual(r.rows,[{patent:'US900B1',change:'记录变化'}]);});
test('legal capability requires status and date on the same source record',async()=>{const records=fixtures.map((p,i)=>({...p,legalStatus:i===0?'Granted':'',legalAsOf:i===1?'2025-01-01':''}));assert.equal((await executeTool('analyze_legal_status',{},meta,records)).status,'unavailable');});
test('year filtering, missing fields, no invented citation/family/legal facts',async()=>{
 const r=await executeTool('analyze_patent_trend',{year_start:2021,year_end:2021},meta,fixtures);assert.deepEqual(r.rows,[{period:'2021',count:1}]);
 const missing=fixtures.map(p=>({...p,ipc:[],citations:[],familyMembers:[],legalStatus:'',legalAsOf:''}));for(const name of ['analyze_ipc_distribution','analyze_citation_network','analyze_family_geography','analyze_legal_status'])assert.equal((await executeTool(name,{},meta,missing)).status,'unavailable');
});
test('monthly trend does not silently truncate after twenty months',async()=>{const records=Array.from({length:36},(_,i)=>({...fixtures[0],id:'TEST'+i,publicationDate:`${2020+Math.floor(i/12)}-${String(i%12+1).padStart(2,'0')}-01`}));const r=await executeTool('analyze_patent_trend',{frequency:'month'},meta,records);assert.equal(r.rows.length,36);assert.equal(r.rows.reduce((s,row)=>s+Number(row.count),0),36);});
test('integer model parameters normalize numeric strings but reject fractions',()=>{assert.equal(paramsSchema.parse({top_k:'10'}).top_k,10);assert.throws(()=>paramsSchema.parse({top_k:1.3}));assert.throws(()=>paramsSchema.parse({top_k:'all'}));});
test('role separation, deterministic clusters, real-edge graph and normalized PageRank',()=>{assert.deepEqual(fixtures[0].applicants,['Alpha','Beta']);assert.deepEqual(fixtures[0].assignees,['Different owner']);assert.deepEqual(fixtures[0].ipc,['G06F16/00']);assert.deepEqual(clusters(fixtures,2),clusters(fixtures,2));const g=citationGraph(fixtures);assert.ok(g.edges.some(e=>e.target==='US901B1'));assert.equal(g.edges.length,4);assert.ok(Math.abs([...pagerank(g).values()].reduce((s,n)=>s+n,0)-1)<1e-9);assert.ok(concentration(fixtures).hhi<=1);});
test('zero lexical matches do not return arbitrary patents',async()=>{assert.equal((await executeTool('search_patents',{query:'photosynthesis'},meta,fixtures)).rows.length,0);});
test('keyword counts are configurable for the corpus and each year',async()=>{const cloud=await executeTool('generate_wordcloud',{top_k:2},meta,fixtures);assert.equal(cloud.rows.length,2);const yearly=await executeTool('analyze_yearly_keywords',{top_k:1},meta,fixtures);const counts=new Map<string,number>();for(const row of yearly.rows)counts.set(String(row.year),(counts.get(String(row.year))||0)+1);assert.ok([...counts.values()].every(n=>n===1));});
test('claim extraction rejects an unlocatable model quote',async()=>{await assert.rejects(()=>executeTool('analyze_claim_elements',{},meta,fixtures,{extract:async()=>[{claim:1,quote:'invented phrase'}]}),/不能定位/);});
test('Google JSONL keeps CPC separate and does not relabel assignees as applicants; duplicate identifiers normalize equally',()=>{const records=importText(JSON.stringify({publication_number:'US-900-B1',title_localized:[{text:'Example',language:'en'}],assignee:['Owner'],cpc:[{code:'H04L9/32'}]})+'\n'+JSON.stringify({id:'US900B1',title:'Example'}),'google','test');assert.equal(new Set(records.map(p=>p.id)).size,1);assert.deepEqual(records[0].applicants,[]);assert.deepEqual(records[0].assignees,['Owner']);assert.deepEqual(records[0].ipc,[]);});
test('USPTO XML parses source roles, dates, claims and citations',()=>{const xml='<?xml version="1.0"?><us-patent-grant><publication-reference><document-id><country>US</country><doc-number>900</doc-number><kind>B1</kind><date>20200101</date></document-id></publication-reference><invention-title>Example</invention-title><abstract><p>Abstract.</p></abstract><applicant><addressbook><orgname>Applicant</orgname></addressbook></applicant><assignee><addressbook><orgname>Owner</orgname></addressbook></assignee><classification-ipcr><section>G</section><class>06</class><subclass>F</subclass><main-group>16</main-group><subgroup>00</subgroup></classification-ipcr><claims><claim num="0001"><claim-text>A test claim.</claim-text></claim></claims><description><p>Original description.</p></description><patcit><document-id><country>US</country><doc-number>800</doc-number><kind>B1</kind></document-id></patcit></us-patent-grant>';const [p]=importText(xml,'xml','test');assert.equal(p.id,'US900B1');assert.equal(p.publicationDate,'2020-01-01');assert.deepEqual(p.applicants,['Applicant']);assert.deepEqual(p.assignees,['Owner']);assert.deepEqual(p.ipc,['G06F16/00']);assert.deepEqual(p.citations,['US800B1']);assert.equal(p.claims[0].number,1);assert.equal(p.rawText,xml);});
test('Derwent/WoS AE is assignee, not applicant; missing claims stay missing',()=>{const [p]=importText('PT J\nPN US900B1\nTI Test title\nAB Test abstract\nAE Owner\nIP G06F16/00\nPD 2020-01-01\nER\n','wos','test');assert.equal(p.id,'US900B1');assert.equal(p.publicationDate,'2020-01-01');assert.deepEqual(p.applicants,[]);assert.deepEqual(p.assignees,['Owner']);assert.deepEqual(p.claims,[]);});
test('USPTO publication XML supports the official us-applicant tag',()=>{const [p]=importText('<?xml version="1.0"?><us-patent-application><publication-reference><document-id><country>US</country><doc-number>20200000900</doc-number><kind>A1</kind><date>20200101</date></document-id></publication-reference><invention-title>Application</invention-title><us-parties><us-applicants><us-applicant><addressbook><orgname>Applicant</orgname></addressbook></us-applicant></us-applicants></us-parties></us-patent-application>','xml','test');assert.equal(p.id,'US20200000900A1');assert.deepEqual(p.applicants,['Applicant']);assert.deepEqual(p.assignees,[]);});
