'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowUp,Square,Maximize2,Minimize2} from 'lucide-react';
export default function PatentComposer({text,onText,onSend,onStop,busy,disabled,stoppable=true}:{text:string;onText:(text:string)=>void;onSend:()=>void;onStop:()=>void;busy:boolean;disabled:boolean;stoppable?:boolean}){
 const textarea=useRef<HTMLTextAreaElement>(null),box=useRef<HTMLFormElement>(null);const [expanded,setExpanded]=useState(false),[long,setLong]=useState(false);
 useEffect(()=>{if(!text)setExpanded(false);},[text]);
 useLayoutEffect(()=>{const el=textarea.current;if(!el)return;const resize=()=>{el.style.height='0px';const natural=el.scrollHeight,viewport=window.visualViewport?.height||innerHeight,cap=expanded?Math.max(96,Math.min(360,viewport*.42)):Math.max(64,Math.min(160,viewport*.24));el.style.height=Math.min(cap,Math.max(40,natural))+'px';el.style.overflowY=natural>cap?'auto':'hidden';setLong(natural>96);};resize();const observer=new ResizeObserver(resize);if(box.current)observer.observe(box.current);window.visualViewport?.addEventListener('resize',resize);return()=>{observer.disconnect();window.visualViewport?.removeEventListener('resize',resize);};},[text,expanded]);
 return <form ref={box} className="patent-composer" onSubmit={e=>{e.preventDefault();if(!disabled&&!busy&&text.trim())onSend();}}><div className="patent-composer-box" data-busy={busy}><textarea ref={textarea} id="question" aria-label="专利分析问题" rows={1} placeholder={disabled?'报告是历史快照，点击新对话继续。':'描述分析问题，可以附上范围、比较对象与报告要求…'} value={text} disabled={disabled} onChange={e=>onText(e.target.value)} onKeyDown={e=>{if(e.nativeEvent.isComposing||e.nativeEvent.keyCode===229)return;if(e.key==='Enter'&&!e.shiftKey&&(e.ctrlKey||e.metaKey||innerWidth>730)){e.preventDefault();if(!disabled&&!busy&&text.trim())onSend();}}}/><div className="patent-composer-tools"><div>{(long||expanded)&&<button type="button" aria-label={expanded?'收起输入框':'展开输入框'} onClick={()=>{setExpanded(v=>!v);textarea.current?.focus();}}>{expanded?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button>}</div>{busy?<button type="button" disabled={!stoppable} onClick={onStop}><Square size={15}/>停止</button>:<button type="submit" className="primary" disabled={disabled||!text.trim()} aria-label="发送问题"><ArrowUp size={20}/></button>}</div></div></form>;
}
