'use client';
import {useMemo,useState} from 'react';
import ClusterView from './ClusterView';
import {BarChart,Bar,LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {Table2,ChartColumn,Network,Download,ChevronDown,ChevronUp} from 'lucide-react';
import type {AnalysisResult,Graph,Row} from '@/lib/types';
const label:Record<string,string>={topic_name:'技术主题',topic_explanation:'主题解释',topic_evidence:'归纳依据专利',topic_basis:'归纳方式',topic_model:'归纳模型',patent:'公开编号',applicant:'申请人',applicants:'申请人',title:'标题',count:'数量',year:'年份',period:'公开时间',score:'筛查分',ipc:'IPC小类',cpc:'CPC',source:'来源',target:'目标',weight:'权重',word:'关键词',documents:'专利数',keywords:'主题关键词',claims:'权利要求',element:'要素',quote:'原文引文',claim:'权利要求编号',summary:'摘要',description:'说明书',field:'字段',coverage:'覆盖率',records:'记录数',indexed:'已索引',type:'类型',pagerank:'PageRank',function:'功能词',effect:'效果词',representative:'代表专利',representatives:'代表专利',status:'来源状态',as_of:'获取日期',basis:'状态依据',event_date:'事件日期',event:'事件',details:'原文详情',member:'同族代表公开件',office:'公开局',family_office:'公开局',family_definition:'同族范围',observed_at:'获取时间',ownership_date:'权属事件日期',ownership_event:'权属事件',ownership_details:'权属原文',reportedAmount:'组合披露金额',currency:'币种',transactionYear:'交易年份',assetScope:'交易范围',pricingBasis:'金额依据',associationBasis:'关联依据',limitation:'适用限制',economic_value:'单项专利估值',sourceUrl:'来源链接',retrievedAt:'获取时间',source_url:'来源链接',front:'非支配层',internal_citations:'样本内被引数',internal_pagerank:'样本内 PageRank',pareto_layer:'非支配层',family_size:'同族代表文献数',pareto_front:'非支配层',backward_citations:'后向引证数',reference_dataset_size:'分析记录数',screening_basis:'筛查依据',ownership_count:'权属事件数',claim_count:'权利要求数',publicationDate:'公开日期',assignees:'受让人',abstract:'摘要',public_evidence:'公开资料',claim_offset:'权利要求内位置'};
function columnClass(key:string){return key==='title'?'column-title':['quote','details','ownership_details','limitation','associationBasis','pricingBasis','family_definition'].includes(key)?'column-text':'';}
function display(value:unknown){if(value===null||value===undefined)return '—';if(typeof value==='number')return Number.isInteger(value)?String(value):value.toFixed(4).replace(/0+$/,'').replace(/\.$/,'');if(Array.isArray(value))return value.map(v=>typeof v==='object'?JSON.stringify(v):v).join('; ');return typeof value==='object'?JSON.stringify(value):String(value);}
function download(name:string,data:string,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}
export function DataTable({rows,onPatent}:{rows:Row[];onPatent?:(id:string)=>void}){const [page,setPage]=useState(1);const keys=[...new Set(rows.flatMap(row=>Object.keys(row)))];return <><div className="table-scroll"><table><thead><tr>{keys.map(key=><th key={key} className={columnClass(key)}>{label[key]||key}</th>)}</tr></thead><tbody>{rows.slice((page-1)*15,page*15).map((row,i)=><tr key={i}>{keys.map(key=><td key={key} className={columnClass(key)}>{['patent','representative'].includes(key)&&row[key]?<button className="text-link" onClick={()=>onPatent?.(String(row[key]))}>{display(row[key])}</button>:<span title={display(row[key])}>{display(row[key])}</span>}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="empty">没有符合条件的记录。可调整分析参数后重试。</p>}</div>{rows.length>15&&<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><span>{(page-1)*15+1}—{Math.min(page*15,rows.length)} / {rows.length}</span><button disabled={page*15>=rows.length} onClick={()=>setPage(page+1)}>下一页</button></div>}</>;}
function GraphView({graph,onPatent}:{graph:Graph;onPatent:(id:string)=>void}){
 const [query,setQuery]=useState(''),[selected,setSelected]=useState(''),[scale,setScale]=useState(1);
 const geometry=useMemo(()=>{const connected=new Set(graph.edges.flatMap(e=>[e.source,e.target]));const candidates=graph.nodes.filter(n=>connected.has(n.id));const roots=candidates.filter(n=>query?n.label.toLowerCase().includes(query.toLowerCase()):n.kind!=='external').sort((a,b)=>b.value-a.value).slice(0,8);const rootIds=new Set(roots.map(n=>n.id));const neighbors=new Set(graph.edges.filter(e=>rootIds.has(e.source)||rootIds.has(e.target)).flatMap(e=>[e.source,e.target]));const nodes=[...roots,...candidates.filter(n=>!rootIds.has(n.id)&&neighbors.has(n.id)).sort((a,b)=>b.value-a.value)].slice(0,60);const citation=graph.edges.some(e=>e.kind==='citation');const positions=new Map(nodes.map((n,i)=>{if(citation)return [n.id,rootIds.has(n.id)?{x:85,y:65+roots.indexOf(n)*400/Math.max(1,roots.length-1)}:{x:250+(i-roots.length)%4*96,y:35+Math.floor((i-roots.length)/4)*34}];const angle=i*2.399963229728653;const radius=35+Math.sqrt(i/Math.max(1,nodes.length))*210;return [n.id,{x:320+Math.cos(angle)*radius,y:255+Math.sin(angle)*radius}];}));return {nodes,positions,edges:graph.edges.filter(e=>positions.has(e.source)&&positions.has(e.target))};},[graph,query]);
 const selectedNode=graph.nodes.find(n=>n.id===selected);
 return <><div className="graph-toolbar"><input aria-label="查找图谱节点" placeholder="查找节点…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>setScale(Math.min(2.5,scale+0.25))} aria-label="放大图谱">+</button><button onClick={()=>setScale(Math.max(.5,scale-.25))} aria-label="缩小图谱">−</button><button onClick={()=>setScale(1)}>复位</button><button onClick={e=>{const svg=e.currentTarget.closest('.result-panel')?.querySelector('.graph-svg');if(svg)download('patent-graph.svg',svg.outerHTML,'image/svg+xml');}}><Download size={14}/>导出</button></div>
<svg className="graph-svg" viewBox={`${320-320/scale} ${255-255/scale} ${640/scale} ${510/scale}`} role="img" aria-label="专利关系图谱"><defs><marker id="citation-arrow" viewBox="0 0 10 10" refX="12" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#929c90"/></marker></defs><rect x="-500" y="-500" width="2000" height="2000" fill="#f7f8f5"/>{geometry.edges.map((edge,i)=>{const a=geometry.positions.get(edge.source)!,b=geometry.positions.get(edge.target)!;return <line markerEnd={edge.kind==='citation'?'url(#citation-arrow)':undefined} key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} stroke={selected&&(edge.source===selected||edge.target===selected)?'#3d6859':'#c4cdc1'} strokeWidth={Math.min(3,1+Math.log(edge.weight))}/>;})}{geometry.nodes.map(node=>{const pos=geometry.positions.get(node.id)!;const highlight=query&&node.label.toLowerCase().includes(query.toLowerCase());return <g key={node.id} tabIndex={0} role="button" aria-label={node.label} onClick={()=>setSelected(node.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(node.id);}}}><circle cx={pos.x} cy={pos.y} r={Math.min(16,5+Math.sqrt(node.value))} fill={highlight||selected===node.id?'#3d6859':node.kind==='external'?'#acb5a9':'#667b69'}/><text x={pos.x+9} y={pos.y+4} fill="#303c31" fontSize="10">{node.label.length>24?node.label.slice(0,22)+'…':node.label}</text><title>{node.label}</title></g>;})}</svg>
 {!geometry.nodes.length&&<p className="empty">没有可绘制的关系边；可切换数据表查看统计。</p>}
 <div className="graph-note">全图 {graph.nodes.length} 个节点 / {graph.edges.length} 条边；预览选取最多 8 个来源节点及其真实相邻节点，共 {geometry.nodes.length} 节点、{geometry.edges.length} 边。箭头指向被引文献，灰色为外部节点；查找可切换预览范围。</div>
 {selectedNode&&<div className="node-detail"><strong>{selectedNode.label}</strong><span>{selectedNode.kind==='external'?'外部节点，仅有引用标识':'来源语料节点'} · 权重 {selectedNode.value}</span>{selectedNode.kind==='patent'&&<button onClick={()=>onPatent(selectedNode.id)}>查看专利原文</button>}{selectedNode.kind==='external'&&<a href={`https://patents.google.com/patent/${selectedNode.id}/en`} target="_blank" rel="noreferrer">查询公开文献</a>}</div>}</>;
}
export default function ResultView({result,onPatent}:{result:AnalysisResult;onPatent:(id:string)=>void}){const [tab,setTab]=useState(result.clusterMap?'cluster':result.graph?'graph':result.chart?'chart':'data'),[details,setDetails]=useState(false);const chartRows=result.rows.slice(0,20);const chart=result.chart;return <section className="result-panel"><header><div><span className={`status-dot ${result.status}`}/><h3>{result.title}</h3></div><span className="result-status">{result.status==='completed'?'已完成':result.status==='unavailable'?'数据不足':'执行失败'}</span></header><p>{result.summary}</p><div className="result-tabs">{result.clusterMap&&<button className={tab==='cluster'?'selected':''} onClick={()=>setTab('cluster')}><ChartColumn size={15}/>聚类图</button>}{result.chart&&<button className={tab==='chart'?'selected':''} onClick={()=>setTab('chart')}><ChartColumn size={15}/>图表</button>}{result.graph&&<button className={tab==='graph'?'selected':''} onClick={()=>setTab('graph')}><Network size={15}/>图谱</button>}<button className={tab==='data'?'selected':''} onClick={()=>setTab('data')}><Table2 size={15}/>数据表</button><button className="push-right" onClick={()=>download(result.tool+'.json',JSON.stringify(result,null,2),'application/json')}><Download size={15}/>下载 JSON</button></div>
 {tab==='cluster'&&result.clusterMap&&<ClusterView map={result.clusterMap} rows={result.rows} onPatent={onPatent}/>} {tab==='data'&&<DataTable rows={result.rows} onPatent={onPatent}/>}{tab==='graph'&&result.graph&&<GraphView graph={result.graph} onPatent={onPatent}/>}{tab==='chart'&&chart&&<div className="chart"><ResponsiveContainer width="100%" height={320}>{chart.kind==='line'?<LineChart data={chartRows}><CartesianGrid stroke="#dfe4da" strokeDasharray="3 3"/><XAxis dataKey={chart.x} fontSize={11}/><YAxis fontSize={11}/><Tooltip contentStyle={{background:'#fff',border:'1px solid #d9ddd8',borderRadius:3,fontSize:12}} cursor={{fill:'#eef0ed'}}/><Line type="monotone" dataKey={chart.y} stroke="#556c59" strokeWidth={2} dot/></LineChart>:<BarChart data={chartRows} margin={{bottom:40}}><CartesianGrid stroke="#dfe4da" strokeDasharray="3 3" vertical={false}/><XAxis dataKey={chart.x} fontSize={10} angle={-25} textAnchor="end" interval={0} tickFormatter={v=>String(v).length>18?String(v).slice(0,16)+'…':String(v)}/><YAxis fontSize={11}/><Tooltip contentStyle={{background:'#fff',border:'1px solid #d9ddd8',borderRadius:3,fontSize:12}} cursor={{fill:'#eef0ed'}}/><Bar dataKey={chart.y} fill="#737e74" radius={[3,3,0,0]}/></BarChart>}</ResponsiveContainer></div>}
 <button className="method-toggle" onClick={()=>setDetails(!details)}>{details?<ChevronUp size={14}/>:<ChevronDown size={14}/>}方法与来源</button>{details&&<div className="method"><p>{result.method}</p><ul>{result.warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul><p>数据集版本：{result.datasetId}</p><p>来源记录：{result.evidence.length} 条 <span>{result.evidence.slice(0,5).map(id=><button className="text-link" key={id} onClick={()=>onPatent(id)}>{id}</button>)}</span></p></div>}</section>;}
