'use client';
import {useEffect,useRef,useState} from 'react';
export default function SourceAcquisition({onImported}:{onImported:(id:string)=>void}){const [name,setName]=useState('公开语料采集'),[offset,setOffset]=useState(10000),[batches,setBatches]=useState(1),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState('');const abort=useRef<AbortController|null>(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 async function acquire(){const control=new AbortController();abort.current=control;setBusy(true);setStatus('正在读取公开语料');try{const response=await fetch('/api/acquisition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,offset,batches,query}),signal:control.signal});if(!response.ok||!response.body)throw new Error((await response.json()).error);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const part=await reader.read();buffer+=decoder.decode(part.value||new Uint8Array(),{stream:!part.done});let end;while((end=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,end);buffer=buffer.slice(end+2);const data=JSON.parse(block.split('\n').find(l=>l.startsWith('data: '))!.slice(6));
if(data.error)throw new Error(data.error);
if(data.message)setStatus(data.message);
if(data.done!==undefined)setStatus(`读取窗口 ${data.done}/${data.total}，可用候选 ${data.candidates} 条`);if(data.dataset){setStatus(`已导入 ${data.dataset.count} 条；请建立语义索引后使用语义检索`);onImported(data.dataset.id);}}if(part.done)break;}}catch(e){setStatus(control.signal.aborted?'已停止；已下载窗口保留，下次从相同位置重试可复用':(e as Error).message);}finally{setBusy(false);}}
 return <details className="import-panel"><summary>获取公开专利语料</summary><p>从 ExponentialScience/DLT-Patents 的指定位置读取真实全文记录。每批100条，最多10批，保存为独立数据集，不改写当前数据或旧报告。来源不是全球实时检索服务。</p><div className="scope-fields"><label>数据集名称<input value={name} onChange={e=>setName(e.target.value)}/></label><label>起始源位置<input type="number" min={0} max={49024} value={offset} onChange={e=>setOffset(Number(e.target.value))}/></label><label>批次数<input type="number" min={1} max={10} value={batches} onChange={e=>setBatches(Number(e.target.value))}/></label><label>英文检索词（可留空）<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="blockchain identity authentication"/></label></div><button disabled={busy||!name.trim()} onClick={()=>void acquire()}>获取并导入</button>{busy&&<button onClick={()=>abort.current?.abort()}>停止获取</button>}{status&&<p role="status">{status}</p>}</details>;
}
