import {mkdirSync,writeFileSync} from 'node:fs';
import {questions} from '../src/lib/suggestions';
import type {Run,Params} from '../src/lib/types';
process.loadEnvFile('.env.local');
const base=process.env.VERIFY_BASE||'http://127.0.0.1:3018',out=process.env.VERIFY_OUT||'/home/yao/artifacts/invention-atlas/research-20261009';mkdirSync(out,{recursive:true});let cookie='';
async function api(path:string,body?:unknown,method?:string){const response=await fetch(base+'/api/'+path,{method:method||(body?'POST':'GET'),headers:{cookie,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(path==='login')cookie=(response.headers.get('set-cookie')||'').split(';')[0];const data=await response.json();if(!response.ok)throw new Error(path+': '+data.error);return data;}
await api('login',{username:process.env.PATENT_USERNAME||'jyao',password:process.env.PATENT_PASSWORD});const ds=await api('datasets'),datasetId=ds.active,checks:unknown[]=[];
async function execute(question:string,conversationId?:string,steps?:{tool:string;params:Params}[]){const c=conversationId||((await api('conversations',{datasetId})).id as string),r:Run=await api('runs',{conversationId:c,datasetId,question,...(steps?{steps}: {})});const response=await fetch(base+'/api/runs/'+r.id+'/events',{headers:{cookie},signal:AbortSignal.timeout(420000)});if(!response.body)throw new Error('No SSE');const reader=response.body.getReader();let chunks=0;while(!(await reader.read()).done)chunks++;const finished:Run=await api('runs/'+r.id);writeFileSync(out+'/'+r.id+'.json',JSON.stringify(finished,null,2));if(finished.status!=='completed')throw new Error(question+': '+finished.status+' '+finished.error+' '+finished.results.filter(x=>x.status!=='completed').map(x=>x.summary).join(';'));checks.push({question,runId:r.id,chunks,status:finished.status,scope:finished.scope?.patentIds.length});return finished;}
const first=await execute('先检索当前数据集中数字身份认证相关专利，再只对检索候选集运行 analyze_concentration 和 analyze_ipc_distribution，生成报告。');
if(first.scope?.mode!=='search'||!first.scope.patentIds.length)throw new Error('No search-scoped analysis');for(const r of first.results.filter(r=>r.tool!=='search_patents'))if(!r.scope||r.scope.patentIds.some(id=>!first.scope!.patentIds.includes(id)))throw new Error('Analysis leaked outside research scope');
const second=await execute('继续分析上轮检索结果的公开趋势，运行 analyze_patent_trend，不要重新检索全库。',first.conversationId);if(second.scope?.mode!=='previous'||JSON.stringify(second.scope.patentIds)!==JSON.stringify(first.scope.patentIds))throw new Error('Previous scope not restored');
const comparison=await execute(questions.compare_claims);const result=comparison.results.find(r=>r.tool==='compare_claims');if(!result?.rows.length)throw new Error('No comparison evidence');for(const row of result.rows){const original=await api('patents/'+row.patent+'?dataset='+datasetId);if(!original.claims.find((c:{number:number})=>c.number===row.claim)?.text.includes(row.quote))throw new Error('Unlocatable source evidence');if(row.target_quote){const candidate=await api('patents/'+row.target_patent+'?dataset='+datasetId);if(!candidate.claims.find((c:{number:number})=>c.number===row.target_claim)?.text.includes(row.target_quote))throw new Error('Unlocatable target evidence');}}
await execute(questions.audit_dataset);const evaluation=await api('evaluations/'+first.id);if(evaluation.outcome.human.status!=='pending'||evaluation.outcome.human.precision!==null)throw new Error('Automatic checks falsely claim human accuracy');
const report=await api('reports',{runId:comparison.id});const html=await fetch(base+'/api/reports/'+report.id+'/html',{headers:{cookie}});if(!html.ok||!(await html.text()).includes('target_quote'))throw new Error('Comparison report export missing evidence');
writeFileSync(out+'/research-acceptance.json',JSON.stringify({checks,comparisonRows:result.rows.length,manualValidation:'pending',reportId:report.id},null,2));console.log(JSON.stringify({passed:checks.length,comparisonRows:result.rows.length,manualValidation:'pending'}));
